USE GD2C2023
GO

-- BORRADO DE PROCEDURES/
/*
IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO eliminado')
END
*/ 

/*TODO*/
-----------------------------------------------------------------------------------------------------
/*Borrado de FKS de las tablas si existen*/

/*BORRO CONSTRAINS FK A LA TABLA BARRIO*/
/*DESCOMENTAR CUANDO SE CREE LA PK DE BARRIO Y SU FK A LOCALIDAD */
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BARRIO_LOCALIDAD')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BARRIO DROP CONSTRAINT FK_BARRIO_LOCALIDAD
END
GO

/*BORRO CONSTRAINS FK A LA TABLA VENTA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_COMPRADOR')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA DROP CONSTRAINT FK_VENTA_COMPRADOR
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_ANUNCIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA DROP CONSTRAINT FK_VENTA_ANUNCIO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA DROP CONSTRAINT FK_VENTA_MONEDA
END
GO
/*BORRO CONSTRAINS FK A LA TABLA LOCALIDAD*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_LOCALIDAD_PROVINCIA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.LOCALIDAD DROP CONSTRAINT FK_LOCALIDAD_PROVINCIA
END
GO
/*BORRO CONSTRAINS FK A LA TABLA PAGO_VENTA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_VENTA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA DROP CONSTRAINT FK_PAGO_VENTA_VENTA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA DROP CONSTRAINT FK_PAGO_VENTA_MONEDA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_MEDIOPAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA DROP CONSTRAINT FK_PAGO_VENTA_MEDIOPAGO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_ESTADO_ANUNCIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_ESTADO_ANUNCIO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_AGENTE_INMOBILIARIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_AGENTE_INMOBILIARIO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_TIPO_OPERACION')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_TIPO_OPERACION
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_INMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_INMUEBLE
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_MONEDA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_TIPO_PERIODO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_TIPO_PERIODO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_AGENTE_INMOBILIARIO_SUCURSAL')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO DROP CONSTRAINT FK_AGENTE_INMOBILIARIO_SUCURSAL
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DETALLE_IMPORTE_ALQUILER_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER DROP CONSTRAINT FK_DETALLE_IMPORTE_ALQUILER_ALQUILER
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_ALQUILER_MEDIO_PAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER DROP CONSTRAINT FK_PAGO_ALQUILER_MEDIO_PAGO
END
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_ALQUILER_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER DROP CONSTRAINT FK_PAGO_ALQUILER_ALQUILER
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_SUCURSAL_LOCALIDAD')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.SUCURSAL DROP CONSTRAINT FK_SUCURSAL_LOCALIDAD
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_CARACTERISTICA_INMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA DROP CONSTRAINT FK_INMUEBLE_CARACTERISTICA_INMUEBLE
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_CARACTERISTICA_CARACTERISTICA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA DROP CONSTRAINT FK_INMUEBLE_CARACTERISTICA_CARACTERISTICA
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_AMBIENTE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE DROP CONSTRAINT FK_INMUEBLE_AMBIENTE
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_ESTADO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE DROP CONSTRAINT FK_INMUEBLE_ESTADO
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_TIPOINMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE DROP CONSTRAINT FK_INMUEBLE_TIPOINMUEBLE
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_PROPIETARIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE DROP CONSTRAINT FK_INMUEBLE_PROPIETARIO
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_DISPOSICION')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE DROP CONSTRAINT FK_INMUEBLE_DISPOSICION
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_ORIENTACION')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE DROP CONSTRAINT FK_INMUEBLE_ORIENTACION
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_BARRIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE DROP CONSTRAINT FK_INMUEBLE_BARRIO
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ALQUILER_ESTADO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ALQUILER DROP CONSTRAINT FK_ALQUILER_ESTADO
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ALQUILER_ANUNCIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ALQUILER DROP CONSTRAINT FK_ALQUILER_ANUNCIO
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ALQUILER_INQUILINO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ALQUILER DROP CONSTRAINT FK_ALQUILER_INQUILINO
END
GO

-----------------------------------------------------------------------------------------------------
/*Borrado de tablas*/

IF OBJECT_ID('GUISO_DE_LENTEJAS.TIPO_INMUEBLE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.TIPO_INMUEBLE
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_INMUEBLE eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ALQUILER', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ALQUILER
	PRINT('Tabla GUISO_DE_LENTEJAS.ALQUILER eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.VENTA
	PRINT('Tabla GUISO_DE_LENTEJAS.VENTA eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.COMPRADOR', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.COMPRADOR
	PRINT('Tabla GUISO_DE_LENTEJAS.COMPRADOR eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ORIENTACION', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ORIENTACION
	PRINT('Tabla GUISO_DE_LENTEJAS.ORIENTACION eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.TIPO_PERIODO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.TIPO_PERIODO
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_PERIODO eliminada')
END


IF OBJECT_ID('GUISO_DE_LENTEJAS.ANUNCIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ANUNCIO
	PRINT('Tabla GUISO_DE_LENTEJAS.ANUNCIO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO
	PRINT('Tabla GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER
	PRINT('Tabla GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.TIPO_OPERACION', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.TIPO_OPERACION
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_OPERACION eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.CARACTERISTICA', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.CARACTERISTICA
	PRINT('Tabla GUISO_DE_LENTEJAS.CARACTERISTICA eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ESTADO_ANUNCIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ESTADO_ANUNCIO
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_ANUNCIO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ESTADO_INMUEBLE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ESTADO_INMUEBLE
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_INMUEBLE eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.INMUEBLE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.INMUEBLE
	PRINT('Tabla GUISO_DE_LENTEJAS.INMUEBLE eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.AMBIENTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.AMBIENTE
	PRINT('Tabla GUISO_DE_LENTEJAS.AMBIENTE eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.LOCALIDAD', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.LOCALIDAD
	PRINT('Tabla GUISO_DE_LENTEJAS.LOCALIDAD eliminada')
END


IF OBJECT_ID('GUISO_DE_LENTEJAS.BARRIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BARRIO
	PRINT('Tabla GUISO_DE_LENTEJAS.BARRIO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.PAGO_ALQUILER', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER
	PRINT('Tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.INQUILINO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.INQUILINO
	PRINT('Tabla GUISO_DE_LENTEJAS.INQUILINO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.PROPIETARIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.PROPIETARIO
	PRINT('Tabla GUISO_DE_LENTEJAS.PROPIETARIO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.SUCURSAL', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.SUCURSAL
	PRINT('Tabla GUISO_DE_LENTEJAS.SUCURSAL eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ESTADO_ALQUILER', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ESTADO_ALQUILER
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_ALQUILER eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.AMBIENTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.AMBIENTE
	PRINT('Tabla GUISO_DE_LENTEJAS.AMBIENTE eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MEDIO_DE_PAGO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.MEDIO_DE_PAGO
	PRINT('Tabla GUISO_DE_LENTEJAS.MEDIO_DE_PAGO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.DISPOSICION', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.DISPOSICION
	PRINT('Tabla GUISO_DE_LENTEJAS.DISPOSICION eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA
	PRINT('Tabla GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MONEDA', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.MONEDA
	PRINT('Tabla GUISO_DE_LENTEJAS.MONEDA eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.PAGO_VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.PAGO_VENTA
	PRINT('Tabla GUISO_DE_LENTEJAS.PAGO_VENTA eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.PROVINCIA', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.PROVINCIA
	PRINT('Tabla GUISO_DE_LENTEJAS.PROVINCIA eliminada')
END

-----------------------------------------------------------------------------------------------------
/*BORRADO DE STORED PROCEDURES*/
IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_INMUEBLES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_INMUEBLES
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_INMUEBLES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ANUNCIOS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ANUNCIOS
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ANUNCIOS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ALQUILERES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ALQUILERES
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ALQUILERES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_TIPOS_OPERACIONES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_TIPOS_OPERACIONES
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_TIPOS_OPERACIONES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_CARACTERISTICAS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_CARACTERISTICAS
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_CARACTERISTICAS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_AGENTES_INMOBILIARIOS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_AGENTES_INMOBILIARIOS
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_AGENTES_INMOBILIARIOS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_DETALLES_IMPORTES_ALQUILERES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_DETALLES_IMPORTES_ALQUILERES
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_DETALLES_IMPORTES_ALQUILERES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_ANUNCIOS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ANUNCIOS
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_ANUNCIOS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_MEDIOS_DE_PAGO') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_MEDIOS_DE_PAGO
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_MEDIOS_DE_PAGO eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_AMBIENTES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_AMBIENTES
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_AMBIENTES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_PROPIETARIOS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_PROPIETARIOS
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_PROPIETARIOS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_INQUILINOS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_INQUILINOS
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_INQUILINOS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_SUCURSALES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_SUCURSALES
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_SUCURSALES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_PAGOS_ALQUILER') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_PAGOS_ALQUILER
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_PAGOS_ALQUILER eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_MONEDAS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_MONEDAS
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_MONEDAS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_TIPOS_INMUEBLES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_TIPOS_INMUEBLES
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_TIPOS_INMUEBLES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_PROVINCIAS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_PROVINCIAS
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_PROVINCIAS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_DISPOSICIONES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_DISPOSICIONES
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_DISPOSICIONES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_ORIENTACIONES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ORIENTACIONES
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_ORIENTACIONES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_TIPOS_PERIODOS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_TIPOS_PERIODOS
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_TIPOS_PERIODOS eliminado')
END
/* GUISO_DE_LENTEJAS.MIGRAR_COMPRADOR*/
IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_COMPRADOR') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_COMPRADOR
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_COMPRADOR eliminado')
END
/* GUISO_DE_LENTEJAS.MIGRAR_LOCALIDAD*/
IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_LOCALIDAD') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_LOCALIDAD
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_LOCALIDAD eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_BARRIOS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_BARRIOS
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_BARRIOS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_INMUEBLE_CARACTERISTICAS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_INMUEBLE_CARACTERISTICAS
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_INMUEBLE_CARACTERISTICAS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_INMUEBLES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_INMUEBLES
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_INMUEBLES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_ALQUILERES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ALQUILERES
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_ALQUILERES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_VENTA') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_VENTA
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_VENTA eliminado')
END

-----------------------------------------------------------------------------------------------------
/*BORRADO DE ESQUEMA*/

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'GUISO_DE_LENTEJAS')
BEGIN
   DROP SCHEMA GUISO_DE_LENTEJAS
   PRINT('Esquema GUISO_DE_LENTEJAS borrado')
END
GO
