USE GD2C2023
GO

-- BORRADO DE PROCEDURES/
/*
IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO eliminado')
END
*/ 

/*TODO*/
-----------------------------------------------------------------------------------------------------
/*Borrado de FKS de las tablas si existen*/

/*BORRO CONSTRAINS FK A LA TABLA BARRIO*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BARRIO_LOCALIDAD')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.LOCALIDAD DROP CONSTRAINT FK_BARRIO_LOCALIDAD
END
GO

/*BORRO CONSTRAINS FK A LA TABLA VENTA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_COMPRADOR')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA DROP CONSTRAINT FK_VENTA_COMPRADOR
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_ANUNCIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA DROP CONSTRAINT FK_VENTA_ANUNCIO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA DROP CONSTRAINT FK_VENTA_MONEDA
END
GO
/*BORRO CONSTRAINS FK A LA TABLA LOCALIDAD*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_LOCALIDAD_PROVINCIA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.LOCALIDAD DROP CONSTRAINT FK_LOCALIDAD_PROVINCIA
END
GO
/*BORRO CONSTRAINS FK A LA TABLA PAGO_VENTA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_VENTA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA DROP CONSTRAINT FK_PAGO_VENTA_VENTA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA DROP CONSTRAINT FK_PAGO_VENTA_MONEDA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_MEDIOPAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA DROP CONSTRAINT FK_PAGO_VENTA_MEDIOPAGO
END
GO
/*TODO*/
-----------------------------------------------------------------------------------------------------
/*Borrado de tablas*/

IF OBJECT_ID('GUISO_DE_LENTEJAS.TIPO_INMUEBLE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.TIPO_INMUEBLE
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_INMUEBLE eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ALQUILER', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ALQUILER
	PRINT('Tabla GUISO_DE_LENTEJAS.ALQUILER eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.VENTA
	PRINT('Tabla GUISO_DE_LENTEJAS.VENTA eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.COMPRADOR', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.COMPRADOR
	PRINT('Tabla GUISO_DE_LENTEJAS.COMPRADOR eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ORIENTACION', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ORIENTACION
	PRINT('Tabla GUISO_DE_LENTEJAS.ORIENTACION eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.TIPO_PERIODO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.TIPO_PERIODO
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_PERIODO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.LOCALIDAD', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.LOCALIDAD
	PRINT('Tabla GUISO_DE_LENTEJAS.LOCALIDAD eliminada')
END

/*HOLA
IF OBJECT_ID('GUISO_DE_LENTEJAS.BARRIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BARRIO
	PRINT('Tabla GUISO_DE_LENTEJAS.BARRIO eliminada')
END
*/
/*TODO*/
-----------------------------------------------------------------------------------------------------
/*BORRADO DE ESQUEMA*/

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'GUISO_DE_LENTEJAS')
BEGIN
   DROP SCHEMA GUISO_DE_LENTEJAS
   PRINT('Esquema GUISO_DE_LENTEJAS borrado')
END
GO

