USE GD2C2023
GO  
----------------------------------------------------------------------------------------------------------
/*CREACION DE TABLAS*/

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].TIPO_INMUEBLE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.TIPO_INMUEBLE (
		
        TIPO_INMUEBLE_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        TIPO_INMUEBLE_DESCRIPCION nvarchar(100) NOT NULL,
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_INMUEBLE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PAGO_ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER (
		
        PAGO_ALQUILER_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		PAGO_ALQUILER_FECHA_INICIO datetime NOT NULL,
        PAGO_ALQUILER_FECHA_VENCIMIENTO datetime NOT NULL,
		PAGO_ALQUILER_FECHA_PAGO datetime NOT NULL,
		PAGO_ALQUILER_NRO_PERIODO numeric(18,0) NOT NULL,
		PAGO_ALQUILER_DESC_PERIODO nvarchar(100) NOT NULL,
		PAGO_ALQUILER_FECHA_FIN datetime NOT NULL,
		PAGO_ALQUILER_IMPORTE numeric(18,2) NOT NULL,
		PAGO_ALQUILER_MEDIO_PAGO numeric(18,0) NOT NULL,
		PAGO_ALQUILER_ALQUILER numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].INQUILINO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.INQUILINO (
		
        INQUILINO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        INQUILINO_NOMBRE nvarchar(100) NOT NULL,
		INQUILINO_APELLIDO nvarchar(100) NOT NULL,
		INQUILINO_DNI numeric(18,0) NOT NULL,
		INQUILINO_FECHA_REGISTRO datetime NOT NULL,
		INQUILINO_TELEFONO numeric(18,0) NOT NULL,
		INQUILINO_MAIL nvarchar(100) NOT NULL,
		INQUILINO_FECHA_NAC datetime NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.INQUILINO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PROPIETARIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PROPIETARIO (
		
        PROPIETARIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        PROPIETARIO_NOMBRE nvarchar(100) NOT NULL,
		PROPIETARIO_APELLIDO nvarchar(100) NOT NULL,
		PROPIETARIO_DNI numeric(18,0) NOT NULL,
		PROPIETARIO_FECHA_REGISTRO datetime NOT NULL,
		PROPIETARIO_TELEFONO numeric(18,0) NOT NULL,
		PROPIETARIO_MAIL nvarchar(255) NOT NULL,
		PROPIETARIO_FECHA_NAC datetime NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PROPIETARIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].SUCURSAL') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.SUCURSAL (
		
        SUCURSAL_ID numeric(18,0) NOT NULL, --SE OBTIENE DESDE LA TABLA, SUCURSAL CODIGO
        SUCURSAL_NOMBRE nvarchar(100) NOT NULL,
		SUCURSAL_DIRECCION nvarchar(100) NOT NULL,
		SUCURSAL_TELEFONO numeric(18,0) NOT NULL,
		SUCURSAL_LOCALIDAD numeric(18,0) NOT NULL /*REVISAR*/
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.SUCURSAL creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ESTADO_ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ESTADO_ALQUILER (
		
        ESTADO_ALQUILER_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        ESTADO_ALQUILER_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_ALQUILER creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].AMBIENTE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.AMBIENTE (
		
        AMBIENTE_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        AMBIENTE_DESCRIPCION nvarchar(100) NOT NULL  /*EN LA TABLA ORIGINAL ERA INMUEBLE CANTIDAD AMBIENTES*/
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.AMBIENTE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].MEDIO_DE_PAGO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.MEDIO_DE_PAGO (
		
        MEDIO_DE_PAGO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        MEDIO_DE_PAGO_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.MEDIO_DE_PAGO creada')
END
GO

--JUAN

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].MONEDA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.MONEDA (
		
        MONEDA_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        MONEDA_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.MONEDA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].DISPOSICION') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.DISPOSICION (
		
        DISPOSICION_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        DISPOSICION_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.DISPOSICION creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PROVINCIA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PROVINCIA (
		
        PROVINCIA_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        PROVINCIA_NOMBRE nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PROVINCIA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].INMUEBLE_CARACTERISTICA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA (
		
        INMUEBLE_ID numeric(18,0) NOT NULL,
        CARACTERISTICA_ID numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BARRIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BARRIO (
		
        BARRIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        BARRIO_NOMBRE nvarchar(100) NOT NULL,
        BARRIO_LOCALIDAD numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BARRIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].INMUEBLE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.INMUEBLE (
		
        INMUEBLE_NUMERO numeric(18,0) NOT NULL, --NO ES IDENTITY PORQUE VIENE DE LA TABLA MAESTRA
        INMUEBLE_NOMBRE nvarchar(100) NOT NULL, 
        INMUEBLE_DESCRIPCION nvarchar(100) NOT NULL,
        INMUEBLE_SUPERFICIETOTAL numeric(18,2) NOT NULL,
        INMUEBLE_EXPENSAS numeric(18,2) NOT NULL,
        INMUEBLE_ANTIGUEDAD numeric(18,0) NOT NULL,
        INMUEBLE_DIRECCION nvarchar(100) NOT NULL,
        INMUEBLE_AMBIENTE numeric(18,0) NOT NULL,
        INMUEBLE_ESTADO numeric(18,0) NOT NULL,
        INMUEBLE_TIPOINMUEBLE numeric(18,0) NOT NULL,
        INMUEBLE_PROPIETARIO numeric(18,0) NOT NULL,
        INMUEBLE_DISPOSICION numeric(18,0) NOT NULL,   
        INMUEBLE_ORIENTACION numeric(18,0) NOT NULL,
        INMUEBLE_BARRIO numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.INMUEBLE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ALQUILER (
		
        ALQUILER_ID numeric(18,0) NOT NULL, --SE OBTIENE EL CODIGO DE LA TABLA MAESTRA
        ALQUILER_FECHAINICIO datetime NOT NULL,
        ALQUILER_FECHAFIN datetime NOT NULL,
        ALQUILER_DURACION numeric(18,0) NOT NULL,
        ALQUILER_DEPOSITO numeric(18,2) NOT NULL,
        ALQUILER_COMISION numeric(18,2) NOT NULL,
        ALQUILER_GASTOSAVERIGUACIONES numeric(18,2) NOT NULL,
        ALQUILER_ESTADO numeric(18,0) NOT NULL,
        ALQUILER_ANUNCIO numeric(19,0) NOT NULL,
        ALQUILER_INQUILINO numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ALQUILER creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].VENTA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.VENTA (
		
        VENTA_CODIGO numeric(18,0) NOT NULL,
        VENTA_FECHA datetime NOT NULL,
        VENTA_PRECIO numeric(18,2) NOT NULL,
        VENTA_COMISION numeric(18,2) NOT NULL,
        VENTA_COMPRADOR numeric(18,0) NOT NULL,
        VENTA_ANUNCIO numeric(19,0) NOT NULL,
        VENTA_MONEDA numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.VENTA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].COMPRADOR') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.COMPRADOR (
		
        COMPRADOR_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        COMPRADOR_NOMBRE nvarchar(100) NOT NULL,
        COMPRADOR_APELLIDO nvarchar(100) NOT NULL,
        COMPRADOR_DNI numeric(18,0) NOT NULL,
        COMPRADOR_TELEFONO numeric(18,0) NOT NULL,
        COMPRADOR_MAIL nvarchar(100) NOT NULL,
        COMPRADOR_FECHA_NACIMIENTO datetime NOT NULL,
		COMPRADOR_FECHA_REGISTRO datetime NOT NULL
		)
	PRINT('Tabla GUISO_DE_LENTEJAS.COMPRADOR creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ORIENTACION') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ORIENTACION (
		
        ORIENTACION_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        ORIENTACION_DESCRIPCION nvarchar(100) NOT NULL,
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ORIENTACION creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].TIPO_PERIODO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.TIPO_PERIODO (
		
        TIPO_PERIODO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        TIPO_PERIODO_DESCRIPCION nvarchar(100) NOT NULL,
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_PERIODO creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].LOCALIDAD') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.LOCALIDAD (
		
        LOCALIDAD_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        LOCALIDAD_NOMBRE nvarchar(100) NOT NULL,
		LOCALIDAD_PROVINCIA numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.LOCALIDAD creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PAGO_VENTA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PAGO_VENTA (
		
        PAGO_VENTA_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        PAGO_VENTA_IMPORTE numeric(18,2) NOT NULL,
		PAGO_VENTA_VENTA numeric(18,0) NOT NULL,
		PAGO_VENTA_MONEDA numeric(18,0) NOT NULL,
		PAGO_VENTA_MEDIOPAGO numeric(18,0) NOT NULL,
		PAGO_VENTA_COTIZACION numeric(18,2) NOT NULL

	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PAGO_VENTA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ANUNCIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ANUNCIO (
		ANUNCIO_ID numeric(19,0) NOT NULL, --NO ES IDENTITY PORQUE VIENE DE LA TABLA MAESTRA
		ANUNCIO_FECHA_PUBLICACION datetime NOT NULL,
		ANUNCIO_PRECIO_PUBLICADO numeric(18,2) NOT NULL,
		ANUNCIO_ESTADO numeric(18,0) NOT NULL,
		ANUNCIO_FECHA_FINALIZACION datetime NOT NULL,
		ANUNCIO_COSTO_PUBLICACION numeric(18,2) NOT NULL,
		ANUNCIO_AGENTE_INMOBILIARIO numeric(18,0) NOT NULL,
		ANUNCIO_TIPO_OPERACION numeric(18,0) NOT NULL,
		ANUNCIO_INMUEBLE numeric(18,0) NOT NULL,
		ANUNCIO_MONEDA numeric(18,0) NOT NULL,
		ANUNCIO_TIPO_PERIODO numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ANUNCIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].AGENTE_INMOBILIARIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO (
		AGENTE_INMOBILIARIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		AGENTE_INMOBILIARIO_NOMBRE nvarchar(100) NOT NULL, 
		AGENTE_INMOBILIARIO_APELLIDO nvarchar(100) NOT NULL,
		AGENTE_INMOBILIARIO_DNI numeric(18,0) NOT NULL,
		AGENTE_INMOBILIARIO_TELEFONO numeric(18,0) NOT NULL,
		AGENTE_INMOBILIARIO_MAIL nvarchar(100) NOT NULL,
		AGENTE_INMOBILIARIO_FECHA_NACIMIENTO datetime NOT NULL,
		AGENTE_INMOBILIARIO_FECHA_REGISTRO datetime NOT NULL,
		AGENTE_INMOBILIARIO_SUCURSAL numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].DETALLE_IMPORTE_ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER (
		DETALLE_IMPORTE_ALQUILER_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		DETALLE_IMPORTE_ALQUILER_NRO_PERIODO_INICIO numeric(18,0) NOT NULL,
		DETALLE_IMPORTE_ALQUILER_NRO_PERIODO_FIN numeric(18,0) NOT NULL,
		DETALLE_IMPORTE_ALQUILER_PRECIO numeric(18,2) NOT NULL,
		DETALLE_IMPORTE_ALQUILER_ALQUILER numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].TIPO_OPERACION') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.TIPO_OPERACION (
		TIPO_OPERACION_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		TIPO_OPERACION_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_OPERACION creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].CARACTERISTICA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.CARACTERISTICA (
		CARACTERISTICA_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		CARACTERISTICA_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.CARACTERISTICA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ESTADO_ANUNCIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ESTADO_ANUNCIO (
		ESTADO_ANUNCIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		ESTADO_ANUNCIO_DESCRIPCION nvarchar(100) NOT NULL --DEBERIA SER UN CHECK?
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_ANUNCIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ESTADO_INMUEBLE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ESTADO_INMUEBLE (
		ESTADO_INMUEBLE_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		ESTADO_INMUEBLE_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_INMUEBLE creada')
END
GO
