USE GD2C2023
GO  
----------------------------------------------------------------------------------------------------------
/*CREACION DE TABLAS*/

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].TIPO_INMUEBLE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.TIPO_INMUEBLE (
		
        TIPO_INMUEBLE_ID decimal(18,0) NOT NULL IDENTITY(1,1),
        TIPO_INMUEBLE_DESCRIPCION nvarchar(100) NOT NULL,
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_INMUEBLE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PAGO_ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER (
		
        PAGO_ALQUILER_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		PAGO_ALQUILER_FECHA_INICIO datetime NOT NULL,
        PAGO_ALQUILER_FECHA_VENCIMIETO datetime NOT NULL,
		PAGO_ALQUILER_FECHA_PAGO datetime NOT NULL,
		PAGO_ALQUILER_NRO_PERIODO numeric(18,0) NOT NULL,
		PAGO_ALQUILER_DESC_PERIODO nvarchar(100) NOT NULL,
		PAGO_ALQUILER_FECHA_FIN datetime NOT NULL,
		PAGO_ALQUILER_IMPORTE numeric(18,2) NOT NULL,
		PAGO_ALQUILER_MEDIO_PAGO numeric(18,0) NOT NULL,
		PAGO_ALQUILER_ALQUILER numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].INQUILINO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.INQUILINO (
		
        INQUILINO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        INQUILINO_NOMBRE nvarchar(100) NOT NULL,
		INQUILINO_APELLIDO nvarchar(100) NOT NULL,
		INQUILINO_DNI numeric(18,0) NOT NULL,
		INQUILINO_FECHA_REGISTRO datetime NOT NULL,
		INQUILINO_TELEFONO numeric(18,0) NOT NULL,
		INQUILINO_MAIL nvarchar(100) NOT NULL,
		INQUILINO_FECHA_NAC datetime NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.INQUILINO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PROPIETARIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PROPIETARIO (
		
        PROPIETARIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        PROPIETARIO_NOMBRE nvarchar(100) NOT NULL,
		PROPIETARIO_APELLIDO nvarchar(100) NOT NULL,
		PROPIETARIO_DNI numeric(18,0) NOT NULL,
		PROPIETARIO_FECHA_REGISTRO datetime NOT NULL,
		PROPIETARIO_TELEFONO numeric(18,0) NOT NULL,
		PROPIETARIO_MAIL nvarchar(255) NOT NULL,
		PROPIETARIO_FECHA_NAC datetime NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PROPIETARIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].SUCURSAL') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.SUCURSAL (
		
        SUCURSAL_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        SUCURSAL_NOMBRE nvarchar(100) NOT NULL,
		SUCURSAL_DIRECCION nvarchar(100) NOT NULL,
		SUCURSAL_TELEFONO numeric(18,0) NOT NULL,
		SUCURSAL_LOCALIDAD numeric(18,0) NOT NULL /*REVISAR*/
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.SUCURSAL creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ESTADO_ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ESTADO_ALQUILER (
		
        ESTADO_ALQUILER_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        ESTADO_ALQUILER_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_ALQUILER creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].AMBIENTE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.AMBIENTE (
		
        AMBIENTE_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        AMBIENTE_DESCRIPCION nvarchar(100) NOT NULL  /*EN LA TABLA ORIGINAL ERA INMUEBLE CANTIDAD AMBIENTES*/
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.AMBIENTE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].MEDIO_DE_PAGO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.MEDIO_DE_PAGO (
		
        MEDIO_DE_PAGO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        MEDIO_DE_PAGO_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.MEDIO_DE_PAGO creada')
END
GO

/*
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BARRIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BARRIO (
		
        BARRIO_ID decimal(18,0) NOT NULL IDENTITY(1,1),
        BARRIO_NOMBRE nvarchar(?) NOT NULL,
        BARRIO_LOCALIDAD decimal(18,0) NOT NULL, --FK A 
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BARRIO creada')
END
GO
*/