USE GD2C2023
GO  
----------------------------------------------------------------------------------------------------------
/*CREANDO CONSTRAINT PK PARA LAS TABLAS DE LA BASE DE DATOS*/

/*AGREGANDO CONSTRAINT PK A LA TABLA BARRIO*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BARRIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.LOCALIDAD
	ADD CONSTRAINT PK_LOCALIDAD PRIMARY KEY (LOCALIDAD_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.LOCALIDAD agregada')
END
GO

