USE GD2C2023
GO  
----------------------------------------------------------------------------------------------------------
/*CREANDO CONSTRAINT PK PARA LAS TABLAS DE LA BASE DE DATOS*/

/*AGREGANDO CONSTRAINT PK A LA TABLA TIPO_INMUEBLE*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_TIPO_INMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.TIPO_INMUEBLE
	ADD CONSTRAINT PK_TIPO_INMUEBLE PRIMARY KEY (TIPO_INMUEBLE_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.TIPO_INMUEBLE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PAGO_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER
	ADD CONSTRAINT PK_PAGO_ALQUILER PRIMARY KEY (PAGO_ALQUILER_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_INQUILINO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INQUILINO
	ADD CONSTRAINT PK_INQUILINO PRIMARY KEY (INQUILINO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.INQUILINO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PROPIETARIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PROPIETARIO
	ADD CONSTRAINT PK_PROPIETARIO PRIMARY KEY (PROPIETARIO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.PROPIETARIO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_SUCURSAL')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.SUCURSAL
	ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (SUCURSAL_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.SUCURSAL agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_ESTADO_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ESTADO_ALQUILER
	ADD CONSTRAINT PK_ESTADO_ALQUILER PRIMARY KEY (ESTADO_ALQUILER_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.ESTADO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_AMBIENTE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.AMBIENTE
	ADD CONSTRAINT PK_AMBIENTE PRIMARY KEY (AMBIENTE_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.AMBIENTE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MEDIO_DE_PAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.MEDIO_DE_PAGO
	ADD CONSTRAINT PK_MEDIO_DE_PAGO PRIMARY KEY (MEDIO_DE_PAGO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.MEDIO_DE_PAGO agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA BARRIO*/
/*
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BARRIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.LOCALIDAD
	ADD CONSTRAINT PK_LOCALIDAD PRIMARY KEY (LOCALIDAD_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.LOCALIDAD agregada')
END
GO
*/
