/*
if not EXISTS (select * )

BEGIN
alter table GUISO_DE_LENTEJAS.BARRIO
ADD CONSTRAINS FK_BARRIO_LOCALIDAD FOREIGN KEY(BARRIO_LOCALIDAD) REFE
*/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_ALQUILER_MEDIO_PAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER
	ADD CONSTRAINT FK_PAGO_ALQUILER_MEDIO_PAGO FOREIGN KEY (PAGO_ALQUILER_MEDIO_PAGO) REFERENCES GUISO_DE_LENTEJAS.MEDIO_DE_PAGO(MEDIO_DE_PAGO_ID)
	PRINT('Foreign key de MEDIO PAGO de la tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_ALQUILER_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER
	ADD CONSTRAINT FK_PAGO_ALQUILER_ALQUILER FOREIGN KEY (PAGO_ALQUILER_MEDIO_PAGO) REFERENCES GUISO_DE_LENTEJAS.ALQUILER(ALQUILER_ID)
	PRINT('Foreign key de MEDIO PAGO de la tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_SUCURSAL_LOCALIDAD')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.SUCURSAL
	ADD CONSTRAINT FK_SUCURSAL_LOCALIDAD FOREIGN KEY (SUCURSAL_LOCALIDAD) REFERENCES GUISO_DE_LENTEJAS.LOCALIDAD(LOCALIDAD_ID)
	PRINT('Foreign key de LOCALIDAD de la tabla GUISO_DE_LENTEJAS.SUCURSAL agregada')
END
GO