-----------------------------------------------------------------------------------------------------
/*MIGRACION DE TABLAS*/
CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_INMUEBLES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.ESTADO_INMUEBLE (ESTADO_INMUEBLE_DESCRIPCION)
        SELECT DISTINCT(INMUEBLE_ESTADO) from GD2C2023.gd_esquema.Maestra WHERE INMUEBLE_ESTADO IS NOT NULL
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_INMUEBLES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ANUNCIOS
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.ESTADO_ANUNCIO (ESTADO_ANUNCIO_DESCRIPCION)
        SELECT DISTINCT(ANUNCIO_ESTADO) from GD2C2023.gd_esquema.Maestra WHERE ANUNCIO_ESTADO IS NOT NULL
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ANUNCIOS ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ALQUILERES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.ESTADO_ALQUILER (ESTADO_ALQUILER_DESCRIPCION)
        SELECT DISTINCT(ALQUILER_ESTADO) from GD2C2023.gd_esquema.Maestra WHERE ALQUILER_ESTADO IS NOT NULL
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ALQUILERES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_TIPOS_OPERACIONES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.TIPO_OPERACION (TIPO_OPERACION_DESCRIPCION)
        SELECT DISTINCT (ANUNCIO_TIPO_OPERACION) FROM GD2C2023.gd_esquema.Maestra WHERE ANUNCIO_TIPO_OPERACION IS NOT NULL
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_TIPOS_OPERACIONES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_CARACTERISTICAS
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.CARACTERISTICA (CARACTERISTICA_DESCRIPCION)
        VALUES('Cable'),('Calefaccion'),('Wifi'),('Gas')
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_CARACTERISTICAS ejecutado')
GO

--PROBARLO CUANDO LA TABLA SUCURSAL ESTE MIGRADA
/* 
CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_AGENTES_INMOBILIARIOS
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO (AGENTE_INMOBILIARIO_NOMBRE, 
                                                            AGENTE_INMOBILIARIO_APELLIDO, 
                                                            AGENTE_INMOBILIARIO_DNI, 
                                                            AGENTE_INMOBILIARIO_MAIL,
                                                            AGENTE_INMOBILIARIO_TELEFONO,
                                                            AGENTE_INMOBILIARIO_FECHA_NACIMIENTO,
                                                            AGENTE_INMOBILIARIO_FECHA_REGISTRO,
                                                            AGENTE_INMOBILIARIO_SUCURSAL)
       SELECT  DISTINCT M.AGENTE_NOMBRE, M.AGENTE_APELLIDO, M.AGENTE_DNI,
		                M.AGENTE_MAIL,M.AGENTE_TELEFONO,M.AGENTE_FECHA_NAC,
                        M.AGENTE_FECHA_REGISTRO,
                        (SELECT SUCURSAL_ID FROM GUISO_DE_LENTEJAS.SUCURSAL WHERE M.SUCURSAL_CODIGO = SUCURSAL_ID)
                        FROM GD2C2023.gd_esquema.Maestra M
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_AGENTES_INMOBILIARIOS ejecutado')
GO
*/
--PROBAR CUANDO LA TABLA ALQUIER ESTE MIGRADA
/*
CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_DETALLES_IMPORTES_ALQUILERES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER (DETALLE_IMPORTE_ALQUILER_NRO_PERIODO_INICIO,
                                                                DETALLE_IMPORTE_ALQUILER_NRO_PERIODO_FIN,
                                                                DETALLE_IMPORTE_ALQUILER_PRECIO,
                                                                DETALLE_IMPORTE_ALQUILER_ALQUILER)
        SELECT DISTINCT 
               DETALLE_ALQ_NRO_PERIODO_FIN, 
               DETALLE_ALQ_NRO_PERIODO_FIN, 
               DETALLE_ALQ_PRECIO, 
               ALQUILER_CODIGO 
			   FROM GD2C2023.gd_esquema.Maestra
			   WHERE DETALLE_ALQ_NRO_PERIODO_INI IS NOT NULL AND DETALLE_ALQ_NRO_PERIODO_FIN IS NOT NULL

    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_DETALLES_IMPORTES_ALQUILERES ejecutado')
GO
*/
--PROBARLO CUANDO ESTEN MIGRADAS LAS TABLAS MONEDA, TIPO_PERIODO, AGENTE_INMOBILIARIO Y INMUEBLE
/*
CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ANUNCIOS
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.MIGRAR_ANUNCIOS  (ANUNCIO_FECHA_PUBLICACION,
                                                        ANUNCIO_PRECIO_PUBLICADO,
                                                        ANUNCIO_ESTADO,
                                                        ANUNCIO_FECHA_FINALIZACION,
                                                        ANUNCIO_COSTO_PUBLICACION,
                                                        ANUNCIO_AGENTE_INMOBILIARIO,
                                                        ANUNCIO_TIPO_OPERACION,
                                                        ANUNCIO_INMUEBLE,
                                                        ANUNCIO_MONEDA,
                                                        ANUNCIO_TIPO_PERIODO)
        SELECT DISTINCT 
                M.ANUNCIO_FECHA_PUBLICACION, 
                M.ANUNCIO_PRECIO_PUBLICADO, 
                (SELECT ESTADO_ANUNCIO_ID FROM GUISO_DE_LENTEJAS.ESTADO_ANUNCIO WHERE ESTADO_ANUNCIO_DESCRIPCION = M.ANUNCIO_ESTADO) AS ESTADO_ANUNCIO_ID, 
                M.ANUNCIO_FECHA_FINALIZACION,
                M.ANUNCIO_COSTO_ANUNCIO, 
                (SELECT AGENTE_INMOBILIARIO_ID FROM GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO WHERE M.AGENTE_NOMBRE = AGENTE_INMOBILIARIO_NOMBRE AND M.AGENTE_APELLIDO = AGENTE_INMOBILIARIO_APELLIDO AND M.AGENTE_DNI = AGENTE_INMOBILIARIO_DNI) AS AGENTE_INMOBILIARIO_ID,
                (SELECT TIPO_OPERACION_ID FROM GUISO_DE_LENTEJAS.TIPO_OPERACION WHERE M.ANUNCIO_TIPO_OPERACION = TIPO_OPERACION_DESCRIPCION) AS TIPO_OPERACION_ID, 
                M.INMUEBLE_CODIGO,
                (SELECT MONEDA_CODIGO FROM GUISO_DE_LENTEJAS.MONEDA WHERE M.ANUNCIO_MONEDA = MONEDA_CODIGO) AS MONEDA_ID,
                (SELECT TIPO_PERIODO_ID FROM GUISO_DE_LENTEJAS.TIPO_PERIODO WHERE M.ANUNCIO_TIPO_PERIODO = TIPO_PERIODO_DESCRIPCION) AS TIPO_PERIODO_ID
                FROM GD2C2023.gd_esquema.Maestra M
                WHERE M.INMUEBLE_CODIGO IS NOT NULL
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_ANUNCIOS ejecutado')
GO
*/
-----------------------------------------------------------------------------------------------------
/*EJECUCION DE PROCEDURES*/
EXECUTE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_INMUEBLES

EXECUTE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ANUNCIOS

EXECUTE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ALQUILERES

EXECUTE GUISO_DE_LENTEJAS.MIGRAR_TIPOS_OPERACIONES

EXECUTE GUISO_DE_LENTEJAS.MIGRAR_CARACTERISTICAS

--EXECUTE GUISO_DE_LENTEJAS.MIGRAR_AGENTES_INMOBILIARIOS

--EXECUTE GUISO_DE_LENTEJAS.MIGRAR_DETALLES_IMPORTES_ALQUILERES

--EXECUTE GUISO_DE_LENTEJAS.MIGRAR_ANUNCIOS