-----------------------------------------------------------------------------------------------------
/*MIGRACION DE TABLAS*/
CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_INMUEBLES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.ESTADO_INMUEBLE (ESTADO_INMUEBLE_DESCRIPCION)
        SELECT DISTINCT(INMUEBLE_ESTADO) from GD2C2023.gd_esquema.Maestra WHERE INMUEBLE_ESTADO IS NOT NULL
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_INMUEBLES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ANUNCIOS
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.ESTADO_ANUNCIO (ESTADO_ANUNCIO_DESCRIPCION)
        SELECT DISTINCT(ANUNCIO_ESTADO) from GD2C2023.gd_esquema.Maestra WHERE ANUNCIO_ESTADO IS NOT NULL
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ANUNCIOS ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ALQUILERES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.ESTADO_ALQUILER (ESTADO_ALQUILER_DESCRIPCION)
        SELECT DISTINCT(ALQUILER_ESTADO) from GD2C2023.gd_esquema.Maestra WHERE ALQUILER_ESTADO IS NOT NULL
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ALQUILERES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_TIPOS_OPERACIONES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.TIPO_OPERACION (TIPO_OPERACION_DESCRIPCION)
        SELECT DISTINCT (ANUNCIO_TIPO_OPERACION) FROM GD2C2023.gd_esquema.Maestra WHERE ANUNCIO_TIPO_OPERACION IS NOT NULL
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.MIGRAR_TIPOS_OPERACIONES ejecutado')
GO
-----------------------------------------------------------------------------------------------------
/*EJECUCION DE PROCEDURES*/
EXECUTE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_INMUEBLES

EXECUTE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ANUNCIOS

EXECUTE GUISO_DE_LENTEJAS.MIGRAR_ESTADOS_ALQUILERES

EXECUTE GUISO_DE_LENTEJAS.MIGRAR_TIPOS_OPERACIONES