USE GD2C2023
GO

-- BORRADO DE PROCEDURES/
/*
IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO eliminado')
END
*/ 

/*TODO*/
-----------------------------------------------------------------------------------------------------
/*Borrado de FKS de las tablas si existen*/

/*BORRO CONSTRAINS FK A LA TABLA BARRIO*/
/*DESCOMENTAR CUANDO SE CREE LA PK DE BARRIO Y SU FK A LOCALIDAD */
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BARRIO_LOCALIDAD')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BARRIO DROP CONSTRAINT FK_BARRIO_LOCALIDAD
END
GO

/*BORRO CONSTRAINS FK A LA TABLA VENTA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_COMPRADOR')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA DROP CONSTRAINT FK_VENTA_COMPRADOR
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_ANUNCIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA DROP CONSTRAINT FK_VENTA_ANUNCIO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_VENTA_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA DROP CONSTRAINT FK_VENTA_MONEDA
END
GO
/*BORRO CONSTRAINS FK A LA TABLA LOCALIDAD*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_LOCALIDAD_PROVINCIA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.LOCALIDAD DROP CONSTRAINT FK_LOCALIDAD_PROVINCIA
END
GO
/*BORRO CONSTRAINS FK A LA TABLA PAGO_VENTA*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_VENTA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA DROP CONSTRAINT FK_PAGO_VENTA_VENTA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA DROP CONSTRAINT FK_PAGO_VENTA_MONEDA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_MEDIOPAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA DROP CONSTRAINT FK_PAGO_VENTA_MEDIOPAGO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_ESTADO_ANUNCIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_ESTADO_ANUNCIO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_AGENTE_INMOBILIARIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_AGENTE_INMOBILIARIO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_TIPO_OPERACION')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_TIPO_OPERACION
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_INMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_INMUEBLE
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_MONEDA
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_ANUNCIO_TIPO_PERIODO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO DROP CONSTRAINT FK_ANUNCIO_TIPO_PERIODO
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_AGENTE_INMOBILIARIO_SUCURSAL')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO DROP CONSTRAINT FK_AGENTE_INMOBILIARIO_SUCURSAL
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_DETALLE_IMPORTE_ALQUILER_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER DROP CONSTRAINT FK_DETALLE_IMPORTE_ALQUILER_ALQUILER
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_ALQUILER_MEDIO_PAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ALQUILER DROP CONSTRAINT FK_PAGO_ALQUILER_MEDIO_PAGO
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_ALQUILER_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ALQUILER DROP CONSTRAINT FK_PAGO_ALQUILER_ALQUILER
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_SUCURSAL_LOCALIDAD')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.SUCURSAL DROP CONSTRAINT FK_SUCURSAL_LOCALIDAD
END
GO
/*TODO*/
-----------------------------------------------------------------------------------------------------
/*Borrado de tablas*/

IF OBJECT_ID('GUISO_DE_LENTEJAS.TIPO_INMUEBLE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.TIPO_INMUEBLE
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_INMUEBLE eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ALQUILER', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ALQUILER
	PRINT('Tabla GUISO_DE_LENTEJAS.ALQUILER eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.VENTA', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.VENTA
	PRINT('Tabla GUISO_DE_LENTEJAS.VENTA eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.COMPRADOR', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.COMPRADOR
	PRINT('Tabla GUISO_DE_LENTEJAS.COMPRADOR eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ORIENTACION', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ORIENTACION
	PRINT('Tabla GUISO_DE_LENTEJAS.ORIENTACION eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.TIPO_PERIODO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.TIPO_PERIODO
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_PERIODO eliminada')
END


IF OBJECT_ID('GUISO_DE_LENTEJAS.ANUNCIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ANUNCIO
	PRINT('Tabla GUISO_DE_LENTEJAS.ANUNCIO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO
	PRINT('Tabla GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER
	PRINT('Tabla GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.TIPO_OPERACION', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.TIPO_OPERACION
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_OPERACION eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.CARACTERISTICA', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.CARACTERISTICA
	PRINT('Tabla GUISO_DE_LENTEJAS.CARACTERISTICA eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ESTADO_ANUNCIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ESTADO_ANUNCIO
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_ANUNCIO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ESTADO_INMUEBLE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ESTADO_INMUEBLE
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_INMUEBLE eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.INMUEBLE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.INMUEBLE
	PRINT('Tabla GUISO_DE_LENTEJAS.INMUEBLE eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.AMBIENTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.AMBIENTE
	PRINT('Tabla GUISO_DE_LENTEJAS.AMBIENTE eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.LOCALIDAD', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.LOCALIDAD
	PRINT('Tabla GUISO_DE_LENTEJAS.LOCALIDAD eliminada')
END


IF OBJECT_ID('GUISO_DE_LENTEJAS.BARRIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BARRIO
	PRINT('Tabla GUISO_DE_LENTEJAS.BARRIO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.PAGO_ALQUILER', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER
	PRINT('Tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.INQUILINO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.INQUILINO
	PRINT('Tabla GUISO_DE_LENTEJAS.INQUILINO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.PROPIETARIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.PROPIETARIO
	PRINT('Tabla GUISO_DE_LENTEJAS.PROPIETARIO eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.SUCURSAL', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.SUCURSAL
	PRINT('Tabla GUISO_DE_LENTEJAS.SUCURSAL eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.ESTADO_ALQUILER', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.ESTADO_ALQUILER
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_ALQUILER eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.AMBIENTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.AMBIENTE
	PRINT('Tabla GUISO_DE_LENTEJAS.AMBIENTE eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.MEDIO_DE_PAGO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.MEDIO_DE_PAGO
	PRINT('Tabla GUISO_DE_LENTEJAS.MEDIO_DE_PAGO eliminada')
END

/*TODO*/
-----------------------------------------------------------------------------------------------------
/*BORRADO DE ESQUEMA*/

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'GUISO_DE_LENTEJAS')
BEGIN
   DROP SCHEMA GUISO_DE_LENTEJAS
   PRINT('Esquema GUISO_DE_LENTEJAS borrado')
END
GO
USE GD2C2023
GO
----------------------------------------------------------------------------------------------------------
/*CREACION DE ESQUEMA*/
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'GUISO_DE_LENTEJAS')
BEGIN
    EXEC ('CREATE SCHEMA GUISO_DE_LENTEJAS')
	PRINT('Esquema GUISO_DE_LENTEJAS creado')
END
GO
USE GD2C2023
GO  
----------------------------------------------------------------------------------------------------------
/*CREACION DE TABLAS*/

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].TIPO_INMUEBLE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.TIPO_INMUEBLE (
		
        TIPO_INMUEBLE_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        TIPO_INMUEBLE_DESCRIPCION nvarchar(100) NOT NULL,
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_INMUEBLE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PAGO_ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER (
		
        PAGO_ALQUILER_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		PAGO_ALQUILER_FECHA_INICIO datetime NOT NULL,
        PAGO_ALQUILER_FECHA_VENCIMIENTO datetime NOT NULL,
		PAGO_ALQUILER_FECHA_PAGO datetime NOT NULL,
		PAGO_ALQUILER_NRO_PERIODO numeric(18,0) NOT NULL,
		PAGO_ALQUILER_DESC_PERIODO nvarchar(100) NOT NULL,
		PAGO_ALQUILER_FECHA_FIN datetime NOT NULL,
		PAGO_ALQUILER_IMPORTE numeric(18,2) NOT NULL,
		PAGO_ALQUILER_MEDIO_PAGO numeric(18,0) NOT NULL,
		PAGO_ALQUILER_ALQUILER numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].INQUILINO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.INQUILINO (
		
        INQUILINO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        INQUILINO_NOMBRE nvarchar(100) NOT NULL,
		INQUILINO_APELLIDO nvarchar(100) NOT NULL,
		INQUILINO_DNI numeric(18,0) NOT NULL,
		INQUILINO_FECHA_REGISTRO datetime NOT NULL,
		INQUILINO_TELEFONO numeric(18,0) NOT NULL,
		INQUILINO_MAIL nvarchar(100) NOT NULL,
		INQUILINO_FECHA_NAC datetime NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.INQUILINO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PROPIETARIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PROPIETARIO (
		
        PROPIETARIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        PROPIETARIO_NOMBRE nvarchar(100) NOT NULL,
		PROPIETARIO_APELLIDO nvarchar(100) NOT NULL,
		PROPIETARIO_DNI numeric(18,0) NOT NULL,
		PROPIETARIO_FECHA_REGISTRO datetime NOT NULL,
		PROPIETARIO_TELEFONO numeric(18,0) NOT NULL,
		PROPIETARIO_MAIL nvarchar(255) NOT NULL,
		PROPIETARIO_FECHA_NAC datetime NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PROPIETARIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].SUCURSAL') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.SUCURSAL (
		
        SUCURSAL_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        SUCURSAL_NOMBRE nvarchar(100) NOT NULL,
		SUCURSAL_DIRECCION nvarchar(100) NOT NULL,
		SUCURSAL_TELEFONO numeric(18,0) NOT NULL,
		SUCURSAL_LOCALIDAD numeric(18,0) NOT NULL /*REVISAR*/
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.SUCURSAL creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ESTADO_ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ESTADO_ALQUILER (
		
        ESTADO_ALQUILER_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        ESTADO_ALQUILER_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_ALQUILER creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].AMBIENTE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.AMBIENTE (
		
        AMBIENTE_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        AMBIENTE_DESCRIPCION nvarchar(100) NOT NULL  /*EN LA TABLA ORIGINAL ERA INMUEBLE CANTIDAD AMBIENTES*/
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.AMBIENTE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].MEDIO_DE_PAGO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.MEDIO_DE_PAGO (
		
        MEDIO_DE_PAGO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        MEDIO_DE_PAGO_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.MEDIO_DE_PAGO creada')
END
GO

--JUAN

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].MONEDA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.MONEDA (
		
        MONEDA_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        MONEDA_CODIGO nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.MONEDA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].DISPOSICION') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.DISPOSICION (
		
        DISPOSICION_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        DISPOSICION_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.DISPOSICION creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PROVINCIA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PROVINCIA (
		
        PROVINCIA_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        PROVINCIA_NOMBRE nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PROVINCIA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].INMUEBLE_CARACTERISTICA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA (
		
        INMUEBLE_ID numeric(18,0) NOT NULL,
        CARACTERISTICA_ID numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BARRIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BARRIO (
		
        BARRIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        BARRIO_NOMBRE nvarchar(100) NOT NULL,
        BARRIO_LOCALIDAD numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BARRIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].INMUEBLE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.INMUEBLE (
		
        INMUEBLE_NUMERO numeric(18,0) NOT NULL, --NO ES IDENTITY PORQUE VIENE DE LA TABLA MAESTRA
        INMUEBLE_NOMBRE nvarchar(100) NOT NULL, 
        INMUEBLE_DESCRIPCION nvarchar(100) NOT NULL,
        INMUEBLE_SUPERFICIETOTAL numeric(18,2) NOT NULL,
        INMUEBLE_EXPENSAS numeric(18,2) NOT NULL,
        INMUEBLE_ANTIGUEDAD numeric(18,0) NOT NULL,
        INMUEBLE_DIRECCION nvarchar(100) NOT NULL,
        INMUEBLE_AMBIENTE numeric(18,0) NOT NULL,
        INMUEBLE_ESTADO numeric(18,0) NOT NULL,
        INMUEBLE_TIPOINMUEBLE numeric(18,0) NOT NULL,
        INMUEBLE_PROPIETARIO numeric(18,0) NOT NULL,
        INMUEBLE_DISPOSICION numeric(18,0) NOT NULL,   
        INMUEBLE_ORIENTACION numeric(18,0) NOT NULL,
        INMUEBLE_BARRIO numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.INMUEBLE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ALQUILER (
		
        ALQUILER_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        ALQUILER_FECHAINICIO datetime NOT NULL,
        ALQUILER_FECHAFIN datetime NOT NULL,
        ALQUILER_DURACION numeric(18,0) NOT NULL,
        ALQUILER_DEPOSITO numeric(18,2) NOT NULL,
        ALQUILER_COMISION numeric(18,2) NOT NULL,
        ALQUILER_GASTOSAVERIGUACIONES numeric(18,2) NOT NULL,
        ALQUILER_ESTADO numeric(18,0) NOT NULL,
        ALQUILER_ANUNCIO numeric(18,0) NOT NULL,
        ALQUILER_INQUILINO numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ALQUILER creada')
END
GO


/*
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BARRIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BARRIO (
		
        BARRIO_ID decimal(18,0) NOT NULL IDENTITY(1,1),
        BARRIO_NOMBRE nvarchar(?) NOT NULL,
        BARRIO_LOCALIDAD decimal(18,0) NOT NULL, --FK A 
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BARRIO creada')
END
GO
*/

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].VENTA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.VENTA (
		
        VENTA_CODIGO numeric(18,0) NOT NULL,
        VENTA_FECHA datetime NOT NULL,
        VENTA_PRECIO numeric(18,2) NOT NULL,
        VENTA_COMISION numeric(18,2) NOT NULL,
        VENTA_COMPRADOR numeric(18,0) NOT NULL,
        VENTA_ANUNCIO numeric(19,0) NOT NULL,
        VENTA_MONEDA numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.VENTA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].COMPRADOR') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.COMPRADOR (
		
        COMPRADOR_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        COMPRADOR_NOMBRE nvarchar(100) NOT NULL,
        COMPRADOR_APELLIDO nvarchar(100) NOT NULL,
        COMPRADOR_DNI numeric(18,0) NOT NULL,
        COMPRADOR_TELEFONO numeric(18,0) NOT NULL,
        COMPRADOR_MAIL nvarchar(100) NOT NULL,
        COMPRADOR_FECHA_NACIMIENTO datetime NOT NULL,
		COMPRADOR_FECHA_REGISTRO datetime NOT NULL
		)
	PRINT('Tabla GUISO_DE_LENTEJAS.COMPRADOR creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ORIENTACION') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ORIENTACION (
		
        ORIENTACION_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        ORIENTACION_DESCRIPCION nvarchar(100) NOT NULL,
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ORIENTACION creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].TIPO_PERIODO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.TIPO_PERIODO (
		
        TIPO_PERIODO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        TIPO_PERIODO_DESCRIPCION nvarchar(100) NOT NULL,
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_PERIODO creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].LOCALIDAD') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.LOCALIDAD (
		
        LOCALIDAD_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        LOCALIDAD_NOMBRE nvarchar(100) NOT NULL,
		LOCALIDAD_PROVINCIA numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.LOCALIDAD creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PAGO_VENTA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PAGO_VENTA (
		
        PAGO_VENTA_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        PAGO_VENTA_IMPORTE numeric(18,2) NOT NULL,
		PAGO_VENTA_VENTA numeric(18,0) NOT NULL,
		PAGO_VENTA_MONEDA numeric(18,0) NOT NULL,
		PAGO_VENTA_MEDIOPAGO numeric(18,0) NOT NULL,
		PAGO_VENTA_COTIZACION numeric(18,2) NOT NULL

	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PAGO_VENTA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ANUNCIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ANUNCIO (
		ANUNCIO_ID numeric(19,0) NOT NULL, --NO ES IDENTITY PORQUE VIENE DE LA TABLA MAESTRA
		ANUNCIO_FECHA_PUBLICACION datetime NOT NULL,
		ANUNCIO_PRECIO_PUBLICADO numeric(18,2) NOT NULL,
		ANUNCIO_ESTADO numeric(18,0) NOT NULL,
		ANUNCIO_FECHA_FINALIZACION datetime NOT NULL,
		ANUNCIO_COSTO_PUBLICACION numeric(18,2) NOT NULL,
		ANUNCIO_AGENTE_INMOBILIARIO numeric(18,0) NOT NULL,
		ANUNCIO_TIPO_OPERACION numeric(18,0) NOT NULL,
		ANUNCIO_INMUEBLE numeric(18,0) NOT NULL,
		ANUNCIO_MONEDA numeric(18,0) NOT NULL,
		ANUNCIO_TIPO_PERIODO numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ANUNCIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].AGENTE_INMOBILIARIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO (
		AGENTE_INMOBILIARIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		AGENTE_INMOBILIARIO_NOMBRE nvarchar(100) NOT NULL, 
		AGENTE_INMOBILIARIO_APELLIDO nvarchar(100) NOT NULL,
		AGENTE_INMOBILIARIO_DNI numeric(18,0) NOT NULL,
		AGENTE_INMOBILIARIO_TELEFONO numeric(18,0) NOT NULL,
		AGENTE_INMOBILIARIO_MAIL nvarchar(100) NOT NULL,
		AGENTE_INMOBILIARIO_FECHA_NACIMIENTO datetime NOT NULL,
		AGENTE_INMOBILIARIO_FECHA_REGISTRO datetime NOT NULL,
		AGENTE_INMOBILIARIO_SUCURSAL numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].DETALLE_IMPORTE_ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER (
		DETALLE_IMPORTE_ALQUILER_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		DETALLE_IMPORTE_ALQUILER_NRO_PEDIDO_INICIO numeric(18,0) NOT NULL,
		DETALLE_IMPORTE_ALQUILER_NRO_PEDIDO_FIN numeric(18,0) NOT NULL,
		DETALLE_IMPORTE_ALQUILER_PRECIO numeric(18,2) NOT NULL,
		DETALLE_IMPORTE_ALQUILER_ALQUILER numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].TIPO_OPERACION') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.TIPO_OPERACION (
		TIPO_OPERACION_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		TIPO_OPERACION_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_OPERACION creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].CARACTERISTICA') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.CARACTERISTICA (
		CARACTERISTICA_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		CARACTERISTICA_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.CARACTERISTICA creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ESTADO_ANUNCIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ESTADO_ANUNCIO (
		ESTADO_ANUNCIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		ESTADO_ANUNCIO_DESCRIPCION nvarchar(100) NOT NULL --DEBERIA SER UN CHECK?
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_ANUNCIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ESTADO_INMUEBLE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ESTADO_INMUEBLE (
		ESTADO_INMUEBLE_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		ESTADO_INMUEBLE_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_INMUEBLE creada')
END
GO
USE GD2C2023
GO  
----------------------------------------------------------------------------------------------------------
/*CREANDO CONSTRAINT PK PARA LAS TABLAS DE LA BASE DE DATOS*/

/*AGREGANDO CONSTRAINT PK A LA TABLA TIPO_INMUEBLE*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_TIPO_INMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.TIPO_INMUEBLE
	ADD CONSTRAINT PK_TIPO_INMUEBLE PRIMARY KEY (TIPO_INMUEBLE_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.TIPO_INMUEBLE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PAGO_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER
	ADD CONSTRAINT PK_PAGO_ALQUILER PRIMARY KEY (PAGO_ALQUILER_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_INQUILINO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INQUILINO
	ADD CONSTRAINT PK_INQUILINO PRIMARY KEY (INQUILINO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.INQUILINO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PROPIETARIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PROPIETARIO
	ADD CONSTRAINT PK_PROPIETARIO PRIMARY KEY (PROPIETARIO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.PROPIETARIO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_SUCURSAL')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.SUCURSAL
	ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (SUCURSAL_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.SUCURSAL agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_ESTADO_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ESTADO_ALQUILER
	ADD CONSTRAINT PK_ESTADO_ALQUILER PRIMARY KEY (ESTADO_ALQUILER_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.ESTADO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_AMBIENTE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.AMBIENTE
	ADD CONSTRAINT PK_AMBIENTE PRIMARY KEY (AMBIENTE_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.AMBIENTE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MEDIO_DE_PAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.MEDIO_DE_PAGO
	ADD CONSTRAINT PK_MEDIO_DE_PAGO PRIMARY KEY (MEDIO_DE_PAGO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.MEDIO_DE_PAGO agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA BARRIO*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BARRIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BARRIO
	ADD CONSTRAINT PK_BARRIO PRIMARY KEY (BARRIO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BARRIO agregada')
END
GO


/*AGREGANDO CONSTRAINT PK A LA TABLA VENTA*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_VENTA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA
	ADD CONSTRAINT PK_VENTA PRIMARY KEY (VENTA_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.VENTA agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA COMPRADOR*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_COMPRADOR')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.COMPRADOR
	ADD CONSTRAINT PK_COMPRADOR PRIMARY KEY (COMPRADOR_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.COMPRADOR agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA ORIENTACION*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_ORIENTACION')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ORIENTACION
	ADD CONSTRAINT PK_ORIENTACION PRIMARY KEY (ORIENTACION_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.ORIENTACION agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA TIPO_PERIODO*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_TIPO_PERIODO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.TIPO_PERIODO
	ADD CONSTRAINT PK_TIPO_PERIODO PRIMARY KEY (TIPO_PERIODO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.TIPO_PERIODO agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA LOCALIDAD*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_LOCALIDAD')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.LOCALIDAD
	ADD CONSTRAINT PK_LOCALIDAD PRIMARY KEY (LOCALIDAD_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.LOCALIDAD agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA PAGO_VENTA*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PAGO_VENTA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA
	ADD CONSTRAINT PK_PAGO_VENTA PRIMARY KEY (PAGO_VENTA_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.PAGO_VENTA agregada')
END
GO


IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_ANUNCIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO
	ADD CONSTRAINT PK_ANUNCIO PRIMARY KEY (ANUNCIO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.ANUNCIO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_AGENTE_INMOBILIARIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO
	ADD CONSTRAINT PK_AGENTE_INMOBILIARIO PRIMARY KEY (AGENTE_INMOBILIARIO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_DETALLE_IMPORTE_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER
	ADD CONSTRAINT PK_DETALLE_IMPORTE_ALQUILER PRIMARY KEY (DETALLE_IMPORTE_ALQUILER_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_TIPO_OPERACION')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.TIPO_OPERACION
	ADD CONSTRAINT PK_TIPO_OPERACION PRIMARY KEY (TIPO_OPERACION_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.TIPO_OPERACION agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_CARACTERISTICA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.CARACTERISTICA
	ADD CONSTRAINT PK_CARACTERISTICA PRIMARY KEY (CARACTERISTICA_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.CARACTERISTICA agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_ESTADO_ANUNCIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ESTADO_ANUNCIO
	ADD CONSTRAINT PK_ESTADO_ANUNCIO PRIMARY KEY (ESTADO_ANUNCIO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.ESTADO_ANUNCIO agregada')
END
GO


IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_ESTADO_INMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ESTADO_INMUEBLE
	ADD CONSTRAINT PK_ESTADO_INMUEBLE PRIMARY KEY (ESTADO_INMUEBLE_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.ESTADO_INMUEBLE agregada')
END
GO


IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.MONEDA
	ADD CONSTRAINT PK_MONEDA PRIMARY KEY (MONEDA_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.MONEDA agregada')
END
GO


IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_DISPOSICION')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.DISPOSICION
	ADD CONSTRAINT PK_DISPOSICION PRIMARY KEY (DISPOSICION_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.DISPOSICION agregada')
END
GO


IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PROVINCIA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PROVINCIA
	ADD CONSTRAINT PK_PROVINCIA PRIMARY KEY (PROVINCIA_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.PROVINCIA agregada')
END
GO


IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_INMUEBLE_CARACTERISTICA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA
	ADD CONSTRAINT PK_INMUEBLE_CARACTERISTICA PRIMARY KEY (INMUEBLE_ID, CARACTERISTICA_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA agregada')
END
GO


IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_INMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE
	ADD CONSTRAINT PK_INMUEBLE PRIMARY KEY (INMUEBLE_NUMERO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.INMUEBLE agregada')
END
GO


IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ALQUILER
	ADD CONSTRAINT PK_ALQUILER PRIMARY KEY (ALQUILER_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.ALQUILER agregada')
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_ALQUILER_MEDIO_PAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER
	ADD CONSTRAINT FK_PAGO_ALQUILER_MEDIO_PAGO FOREIGN KEY (PAGO_ALQUILER_MEDIO_PAGO) REFERENCES GUISO_DE_LENTEJAS.MEDIO_DE_PAGO(MEDIO_DE_PAGO_ID)
	PRINT('Foreign key de MEDIO PAGO de la tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_ALQUILER_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER
	ADD CONSTRAINT FK_PAGO_ALQUILER_ALQUILER FOREIGN KEY (PAGO_ALQUILER_ALQUILER) REFERENCES GUISO_DE_LENTEJAS.ALQUILER(ALQUILER_ID)
	PRINT('Foreign key de MEDIO PAGO de la tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_SUCURSAL_LOCALIDAD')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.SUCURSAL
	ADD CONSTRAINT FK_SUCURSAL_LOCALIDAD FOREIGN KEY (SUCURSAL_LOCALIDAD) REFERENCES GUISO_DE_LENTEJAS.LOCALIDAD(LOCALIDAD_ID)
	PRINT('Foreign key de LOCALIDAD de la tabla GUISO_DE_LENTEJAS.SUCURSAL agregada')
END
GO

/*AGREGANDO CONSTRAINS FK A LA TABLA VENTA*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_VENTA_COMPRADOR')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA
	ADD CONSTRAINT FK_VENTA_COMPRADOR FOREIGN KEY (VENTA_COMPRADOR) REFERENCES GUISO_DE_LENTEJAS.COMPRADOR(COMPRADOR_ID)
	PRINT('Foreign key de COMPRADOR de la tabla GUISO_DE_LENTEJAS.VENTA agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_VENTA_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA
	ADD CONSTRAINT FK_VENTA_MONEDA FOREIGN KEY (VENTA_MONEDA) REFERENCES GUISO_DE_LENTEJAS.MONEDA(MONEDA_ID)
	PRINT('Foreign key de MONEDA de la tabla GUISO_DE_LENTEJAS.VENTA agregada')
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_VENTA_ANUNCIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.VENTA
	ADD CONSTRAINT FK_VENTA_ANUNCIO FOREIGN KEY (VENTA_ANUNCIO) REFERENCES GUISO_DE_LENTEJAS.ANUNCIO(ANUNCIO_ID)
	PRINT('Foreign key de ANUNCIO de la tabla GUISO_DE_LENTEJAS.VENTA agregada')
END
GO


/*AGREGANDO CONSTRAINS FK A LA TABLA LOCALIDAD*/
/*descomentar cuando este creado la tabla PROVINCIA con pk*/
/*
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_LOCALIDAD_PROVINCIA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.LOCALIDAD
	ADD CONSTRAINT FK_LOCALIDAD_PROVINCIA FOREIGN KEY (LOCALIDAD_PROVINCIA) REFERENCES GUISO_DE_LENTEJAS.PROVINCIA(PROVINCIA_ID)
	PRINT('Foreign key de PROVINCIA de la tabla GUISO_DE_LENTEJAS.LOCALIDAD agregada')
END
GO
*/

/*AGREGANDO CONSTRAINS FK A LA TABLA PAGO_VENTA*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_VENTA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA
	ADD CONSTRAINT FK_PAGO_VENTA_VENTA FOREIGN KEY (PAGO_VENTA_VENTA) REFERENCES GUISO_DE_LENTEJAS.VENTA(VENTA_CODIGO)
	PRINT('Foreign key de VENTA de la tabla GUISO_DE_LENTEJAS.PAGO_VENTA agregada')
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA
	ADD CONSTRAINT FK_PAGO_VENTA_MONEDA FOREIGN KEY (PAGO_VENTA_MONEDA) REFERENCES GUISO_DE_LENTEJAS.MONEDA(MONEDA_ID)
	PRINT('Foreign key de MONEDA de la tabla GUISO_DE_LENTEJAS.PAGO_VENTA agregada')
END
GO


/*descomentar cuando este creado la tabla MEDIOPAGO con pk*/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_VENTA_MEDIOPAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_VENTA
	ADD CONSTRAINT FK_PAGO_VENTA_MEDIOPAGO FOREIGN KEY (PAGO_VENTA_MEDIOPAGO) REFERENCES GUISO_DE_LENTEJAS.MEDIO_DE_PAGO(MEDIO_DE_PAGO_ID)
	PRINT('Foreign key de MEDIO_DE_PAGO de la tabla GUISO_DE_LENTEJAS.PAGO_VENTA agregada')
END
GO


/* FKs TABLA ANUNCIO*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ANUNCIO_ESTADO_ANUNCIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO
	ADD CONSTRAINT FK_ANUNCIO_ESTADO_ANUNCIO FOREIGN KEY (ANUNCIO_ESTADO) REFERENCES GUISO_DE_LENTEJAS.ESTADO_ANUNCIO(ESTADO_ANUNCIO_ID)
	PRINT('Foreign key de ESTADO de la tabla GUISO_DE_LENTEJAS.ANUNCIO agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ANUNCIO_AGENTE_INMOBILIARIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO
	ADD CONSTRAINT FK_ANUNCIO_AGENTE_INMOBILIARIO FOREIGN KEY (ANUNCIO_AGENTE_INMOBILIARIO) REFERENCES GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO(AGENTE_INMOBILIARIO_ID)
	PRINT('Foreign key de AGENTE INMOBILIARIO de la tabla GUISO_DE_LENTEJAS.ANUNCIO agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ANUNCIO_TIPO_OPERACION')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO
	ADD CONSTRAINT FK_ANUNCIO_TIPO_OPERACION FOREIGN KEY (ANUNCIO_TIPO_OPERACION) REFERENCES GUISO_DE_LENTEJAS.TIPO_OPERACION(TIPO_OPERACION_ID)
	PRINT('Foreign key de TIPO OPERACION de la tabla GUISO_DE_LENTEJAS.ANUNCIO agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ANUNCIO_INMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO
	ADD CONSTRAINT FK_ANUNCIO_INMUEBLE FOREIGN KEY (ANUNCIO_INMUEBLE) REFERENCES GUISO_DE_LENTEJAS.INMUEBLE(INMUEBLE_NUMERO)
	PRINT('Foreign key de INMUEBLE de la tabla GUISO_DE_LENTEJAS.ANUNCIO agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ANUNCIO_MONEDA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO
	ADD CONSTRAINT FK_ANUNCIO_MONEDA FOREIGN KEY (ANUNCIO_MONEDA) REFERENCES GUISO_DE_LENTEJAS.MONEDA(MONEDA_ID)
	PRINT('Foreign key de MONEDA de la tabla GUISO_DE_LENTEJAS.ANUNCIO agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ANUNCIO_TIPO_PERIODO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ANUNCIO
	ADD CONSTRAINT FK_ANUNCIO_TIPO_PERIODO FOREIGN KEY (ANUNCIO_TIPO_PERIODO) REFERENCES GUISO_DE_LENTEJAS.TIPO_PERIODO(TIPO_PERIODO_ID)
	PRINT('Foreign key de TIPO PERIODO de la tabla GUISO_DE_LENTEJAS.ANUNCIO agregada')
END
GO

/*FKs TABLA AGENTE INMOBILIARIO*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_AGENTE_INMOBILIARIO_SUCURSAL')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO
	ADD CONSTRAINT FK_AGENTE_INMOBILIARIO_SUCURSAL FOREIGN KEY (AGENTE_INMOBILIARIO_SUCURSAL) REFERENCES GUISO_DE_LENTEJAS.SUCURSAL(SUCURSAL_ID)
	PRINT('Foreign key de SUCURSAL de la tabla GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO agregada')
END
GO

/*FKs TABLA DETALLE IMPORTE ALQUILER*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_DETALLE_IMPORTE_ALQUILER_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER
	ADD CONSTRAINT FK_DETALLE_IMPORTE_ALQUILER_ALQUILER FOREIGN KEY (DETALLE_IMPORTE_ALQUILER_ALQUILER) REFERENCES GUISO_DE_LENTEJAS.ALQUILER(ALQUILER_ID)
	PRINT('Foreign key de ALQUILER de la tabla GUISO_DE_LENTEJAS.DETALLE_IMPORTE_ALQUILER agregada')
END
GO

/*FKs TABLA BARRIO*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BARRIO_LOCALIDAD')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BARRIO
	ADD CONSTRAINT FK_BARRIO_LOCALIDAD FOREIGN KEY (BARRIO_LOCALIDAD) REFERENCES GUISO_DE_LENTEJAS.LOCALIDAD(LOCALIDAD_ID)
	PRINT('Foreign key de LOCALIDAD de la tabla GUISO_DE_LENTEJAS.BARRIO agregada')
END
GO

/*FKs TABLA INMUEBLE_CARACTERISTICA*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_CARACTERISTICA_INMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA
	ADD CONSTRAINT FK_INMUEBLE_CARACTERISTICA_INMUEBLE FOREIGN KEY (INMUEBLE_ID) REFERENCES GUISO_DE_LENTEJAS.INMUEBLE(INMUEBLE_NUMERO)
	PRINT('Foreign key de INMUEBLE de la tabla GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_CARACTERISTICA_CARACTERISTICA')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA
	ADD CONSTRAINT FK_INMUEBLE_CARACTERISTICA_CARACTERISTICA FOREIGN KEY (CARACTERISTICA_ID) REFERENCES GUISO_DE_LENTEJAS.CARACTERISTICA(CARACTERISTICA_ID)
	PRINT('Foreign key de CARACTERISTICA de la tabla GUISO_DE_LENTEJAS.INMUEBLE_CARACTERISTICA agregada')
END
GO

/*FKs TABLA INMUEBLE*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_AMBIENTE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE
	ADD CONSTRAINT FK_INMUEBLE_AMBIENTE FOREIGN KEY (INMUEBLE_AMBIENTE) REFERENCES GUISO_DE_LENTEJAS.AMBIENTE(AMBIENTE_ID)
	PRINT('Foreign key de AMBIENTE de la tabla GUISO_DE_LENTEJAS.INMUEBLE agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_ESTADO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE
	ADD CONSTRAINT FK_INMUEBLE_ESTADO FOREIGN KEY (INMUEBLE_ESTADO) REFERENCES GUISO_DE_LENTEJAS.ESTADO_INMUEBLE(ESTADO_INMUEBLE_ID)
	PRINT('Foreign key de ESTADO de la tabla GUISO_DE_LENTEJAS.INMUEBLE agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_TIPOINMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE
	ADD CONSTRAINT FK_INMUEBLE_TIPOINMUEBLE FOREIGN KEY (INMUEBLE_TIPOINMUEBLE) REFERENCES GUISO_DE_LENTEJAS.TIPO_INMUEBLE(TIPO_INMUEBLE_ID)
	PRINT('Foreign key de TIPOINMUEBLE de la tabla GUISO_DE_LENTEJAS.INMUEBLE agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_PROPIETARIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE
	ADD CONSTRAINT FK_INMUEBLE_PROPIETARIO FOREIGN KEY (INMUEBLE_PROPIETARIO) REFERENCES GUISO_DE_LENTEJAS.PROPIETARIO(PROPIETARIO_ID)
	PRINT('Foreign key de PROPIETARIO de la tabla GUISO_DE_LENTEJAS.INMUEBLE agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_DISPOSICION')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE
	ADD CONSTRAINT FK_INMUEBLE_DISPOSICION FOREIGN KEY (INMUEBLE_DISPOSICION) REFERENCES GUISO_DE_LENTEJAS.DISPOSICION(DISPOSICION_ID)
	PRINT('Foreign key de DISPOSICION de la tabla GUISO_DE_LENTEJAS.INMUEBLE agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_ORIENTACION')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE
	ADD CONSTRAINT FK_INMUEBLE_ORIENTACION FOREIGN KEY (INMUEBLE_ORIENTACION) REFERENCES GUISO_DE_LENTEJAS.ORIENTACION(ORIENTACION_ID)
	PRINT('Foreign key de ORIENTACION de la tabla GUISO_DE_LENTEJAS.INMUEBLE agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_INMUEBLE_BARRIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INMUEBLE
	ADD CONSTRAINT FK_INMUEBLE_BARRIO FOREIGN KEY (INMUEBLE_BARRIO) REFERENCES GUISO_DE_LENTEJAS.BARRIO(BARRIO_ID)
	PRINT('Foreign key de BARRIO de la tabla GUISO_DE_LENTEJAS.INMUEBLE agregada')
END
GO

/*FKs TABLA ALQUILER*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ALQUILER_ESTADO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ALQUILER
	ADD CONSTRAINT FK_ALQUILER_ESTADO FOREIGN KEY (ALQUILER_ESTADO) REFERENCES GUISO_DE_LENTEJAS.ESTADO_ALQUILER(ESTADO_ALQUILER_ID)
	PRINT('Foreign key de ESTADO de la tabla GUISO_DE_LENTEJAS.ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ALQUILER_ANUNCIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ALQUILER
	ADD CONSTRAINT FK_ALQUILER_ANUNCIO FOREIGN KEY (ALQUILER_ANUNCIO) REFERENCES GUISO_DE_LENTEJAS.ANUNCIO(ANUNCIO_ID)
	PRINT('Foreign key de ANUNCIO de la tabla GUISO_DE_LENTEJAS.ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_ALQUILER_INQUILINO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ALQUILER
	ADD CONSTRAINT FK_ALQUILER_INQUILINO FOREIGN KEY (ALQUILER_INQUILINO) REFERENCES GUISO_DE_LENTEJAS.INQUILINO(INQUILINO_ID)
	PRINT('Foreign key de INQUILINO de la tabla GUISO_DE_LENTEJAS.ALQUILER agregada')
END
GO
