USE GD2C2023
GO

-- BORRADO DE PROCEDURES/
/*
IF OBJECT_ID('GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO
	PRINT('Procedure GUISO_DE_LENTEJAS.MIGRAR_TABLA_BARRIO eliminado')
END
*/ 

/*TODO*/
-----------------------------------------------------------------------------------------------------
/*Borrado de FKS de las tablas si existen*/

/*BORRO CONSTRAINS FK A LA TABLA BARRIO*/
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BARRIO_LOCALIDAD')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.LOCALIDAD DROP CONSTRAINT FK_BARRIO_LOCALIDAD
END
GO
/*TODO*/
-----------------------------------------------------------------------------------------------------
/*Borrado de tablas*/

IF OBJECT_ID('GUISO_DE_LENTEJAS.TIPO_INMUEBLE', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.TIPO_INMUEBLE
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_INMUEBLE eliminada')
END

/*
IF OBJECT_ID('GUISO_DE_LENTEJAS.BARRIO', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BARRIO
	PRINT('Tabla GUISO_DE_LENTEJAS.BARRIO eliminada')
END
*/
/*TODO*/
-----------------------------------------------------------------------------------------------------
/*BORRADO DE ESQUEMA*/

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'GUISO_DE_LENTEJAS')
BEGIN
   DROP SCHEMA GUISO_DE_LENTEJAS
   PRINT('Esquema GUISO_DE_LENTEJAS borrado')
END
GO

USE GD2C2023
GO
----------------------------------------------------------------------------------------------------------
/*CREACION DE ESQUEMA*/
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'GUISO_DE_LENTEJAS')
BEGIN
    EXEC ('CREATE SCHEMA GUISO_DE_LENTEJAS')
	PRINT('Esquema GUISO_DE_LENTEJAS creado')
END
GO
USE GD2C2023
GO  
----------------------------------------------------------------------------------------------------------
/*CREACION DE TABLAS*/

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].TIPO_INMUEBLE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.TIPO_INMUEBLE (
		
        TIPO_INMUEBLE_ID decimal(18,0) NOT NULL IDENTITY(1,1),
        TIPO_INMUEBLE_DESCRIPCION nvarchar(100) NOT NULL,
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.TIPO_INMUEBLE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PAGO_ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER (
		
        PAGO_ALQUILER_ID numeric(18,0) NOT NULL IDENTITY(1,1),
		PAGO_ALQUILER_FECHA_INICIO datetime NOT NULL,
        PAGO_ALQUILER_FECHA_VENCIMIETO datetime NOT NULL,
		PAGO_ALQUILER_FECHA_PAGO datetime NOT NULL,
		PAGO_ALQUILER_NRO_PERIODO numeric(18,0) NOT NULL,
		PAGO_ALQUILER_DESC_PERIODO nvarchar(100) NOT NULL,
		PAGO_ALQUILER_FECHA_FIN datetime NOT NULL,
		PAGO_ALQUILER_IMPORTE numeric(18,2) NOT NULL,
		PAGO_ALQUILER_MEDIO_PAGO numeric(18,0) NOT NULL,
		PAGO_ALQUILER_ALQUILER numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].INQUILINO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.INQUILINO (
		
        INQUILINO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        INQUILINO_NOMBRE nvarchar(100) NOT NULL,
		INQUILINO_APELLIDO nvarchar(100) NOT NULL,
		INQUILINO_DNI numeric(18,0) NOT NULL,
		INQUILINO_FECHA_REGISTRO datetime NOT NULL,
		INQUILINO_TELEFONO numeric(18,0) NOT NULL,
		INQUILINO_MAIL nvarchar(100) NOT NULL,
		INQUILINO_FECHA_NAC datetime NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.INQUILINO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].PROPIETARIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.PROPIETARIO (
		
        PROPIETARIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        PROPIETARIO_NOMBRE nvarchar(100) NOT NULL,
		PROPIETARIO_APELLIDO nvarchar(100) NOT NULL,
		PROPIETARIO_DNI numeric(18,0) NOT NULL,
		PROPIETARIO_FECHA_REGISTRO datetime NOT NULL,
		PROPIETARIO_TELEFONO numeric(18,0) NOT NULL,
		PROPIETARIO_MAIL nvarchar(255) NOT NULL,
		PROPIETARIO_FECHA_NAC datetime NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.PROPIETARIO creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].SUCURSAL') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.SUCURSAL (
		
        SUCURSAL_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        SUCURSAL_NOMBRE nvarchar(100) NOT NULL,
		SUCURSAL_DIRECCION nvarchar(100) NOT NULL,
		SUCURSAL_TELEFONO numeric(18,0) NOT NULL,
		SUCURSAL_LOCALIDAD numeric(18,0) NOT NULL /*REVISAR*/
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.SUCURSAL creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].ESTADO_ALQUILER') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.ESTADO_ALQUILER (
		
        ESTADO_ALQUILER_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        ESTADO_ALQUILER_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.ESTADO_ALQUILER creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].AMBIENTE') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.AMBIENTE (
		
        AMBIENTE_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        AMBIENTE_DESCRIPCION nvarchar(100) NOT NULL  /*EN LA TABLA ORIGINAL ERA INMUEBLE CANTIDAD AMBIENTES*/
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.AMBIENTE creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].MEDIO_DE_PAGO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.MEDIO_DE_PAGO (
		
        MEDIO_DE_PAGO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        MEDIO_DE_PAGO_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.MEDIO_DE_PAGO creada')
END
GO

/*
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BARRIO') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BARRIO (
		
        BARRIO_ID decimal(18,0) NOT NULL IDENTITY(1,1),
        BARRIO_NOMBRE nvarchar(?) NOT NULL,
        BARRIO_LOCALIDAD decimal(18,0) NOT NULL, --FK A 
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BARRIO creada')
END
GO
*/USE GD2C2023
GO  
----------------------------------------------------------------------------------------------------------
/*CREANDO CONSTRAINT PK PARA LAS TABLAS DE LA BASE DE DATOS*/

/*AGREGANDO CONSTRAINT PK A LA TABLA TIPO_INMUEBLE*/

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_TIPO_INMUEBLE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.TIPO_INMUEBLE
	ADD CONSTRAINT PK_TIPO_INMUEBLE PRIMARY KEY (TIPO_INMUEBLE_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.TIPO_INMUEBLE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PAGO_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER
	ADD CONSTRAINT PK_PAGO_ALQUILER PRIMARY KEY (PAGO_ALQUILER_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_INQUILINO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.INQUILINO
	ADD CONSTRAINT PK_INQUILINO PRIMARY KEY (INQUILINO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.INQUILINO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_PROPIETARIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PROPIETARIO
	ADD CONSTRAINT PK_PROPIETARIO PRIMARY KEY (PROPIETARIO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.PROPIETARIO agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_SUCURSAL')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.SUCURSAL
	ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (SUCURSAL_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.SUCURSAL agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_ESTADO_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.ESTADO_ALQUILER
	ADD CONSTRAINT PK_ESTADO_ALQUILER PRIMARY KEY (ESTADO_ALQUILER_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.ESTADO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_AMBIENTE')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.AMBIENTE
	ADD CONSTRAINT PK_AMBIENTE PRIMARY KEY (AMBIENTE_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.AMBIENTE agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_MEDIO_DE_PAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.MEDIO_DE_PAGO
	ADD CONSTRAINT PK_MEDIO_DE_PAGO PRIMARY KEY (MEDIO_DE_PAGO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.MEDIO_DE_PAGO agregada')
END
GO

/*AGREGANDO CONSTRAINT PK A LA TABLA BARRIO*/
/*
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BARRIO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.LOCALIDAD
	ADD CONSTRAINT PK_LOCALIDAD PRIMARY KEY (LOCALIDAD_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.LOCALIDAD agregada')
END
GO
*/
/*
if not EXISTS (select * )

BEGIN
alter table GUISO_DE_LENTEJAS.BARRIO
ADD CONSTRAINS FK_BARRIO_LOCALIDAD FOREIGN KEY(BARRIO_LOCALIDAD) REFE
*/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_ALQUILER_MEDIO_PAGO')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER
	ADD CONSTRAINT FK_PAGO_ALQUILER_MEDIO_PAGO FOREIGN KEY (PAGO_ALQUILER_MEDIO_PAGO) REFERENCES GUISO_DE_LENTEJAS.MEDIO_DE_PAGO(MEDIO_DE_PAGO_ID)
	PRINT('Foreign key de MEDIO PAGO de la tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_PAGO_ALQUILER_ALQUILER')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.PAGO_ALQUILER
	ADD CONSTRAINT FK_PAGO_ALQUILER_ALQUILER FOREIGN KEY (PAGO_ALQUILER_MEDIO_PAGO) REFERENCES GUISO_DE_LENTEJAS.ALQUILER(ALQUILER_ID)
	PRINT('Foreign key de MEDIO PAGO de la tabla GUISO_DE_LENTEJAS.PAGO_ALQUILER agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_SUCURSAL_LOCALIDAD')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.SUCURSAL
	ADD CONSTRAINT FK_SUCURSAL_LOCALIDAD FOREIGN KEY (SUCURSAL_LOCALIDAD) REFERENCES GUISO_DE_LENTEJAS.LOCALIDAD(LOCALIDAD_ID)
	PRINT('Foreign key de LOCALIDAD de la tabla GUISO_DE_LENTEJAS.SUCURSAL agregada')
END
GO