--Borrados de FKs tabla hecho operacion
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion DROP CONSTRAINT FK_BI_Hecho_Operacion_Tiempo
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion DROP CONSTRAINT FK_BI_Hecho_Operacion_Tipo_Inmueble
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion DROP CONSTRAINT FK_BI_Hecho_Operacion_Rango_M2
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion DROP CONSTRAINT FK_BI_Hecho_Operacion_Ubicacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tipo_Operacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion DROP CONSTRAINT FK_BI_Hecho_Operacion_Tipo_Operacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Rango_Etario')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion DROP CONSTRAINT FK_BI_Hecho_Operacion_Rango_Etario
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion DROP CONSTRAINT FK_BI_Hecho_Operacion_Sucursal
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion DROP CONSTRAINT FK_BI_Hecho_Operacion_Ambientes
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion DROP CONSTRAINT FK_BI_Hecho_Operacion_Tipo_Moneda
END
GO

--Borrados de FKs tabla hecho anuncio
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Operacion_Tiempo
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Operacion_Tipo_Inmueble
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Operacion_Rango_M2
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Operacion_Tipo_Moneda
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Operacion_Ubicacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tipo_Operacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Operacion_Tipo_Operacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Operacion_Ambientes
END
GO

--Borrado de tablas de hechos

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Hecho_Operacion', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Operacion eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Hecho_Anuncio', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio eliminada')
END

