--PK tabla hecho venta
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Venta')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT PK_BI_Hecho_Venta PRIMARY KEY (VENTA_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

--PK tabla hecho alquiler
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Alquiler')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT PK_BI_Hecho_Alquiler PRIMARY KEY (ALQUILER_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

--PK tabla hecho anuncio
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Anuncio')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT PK_BI_Hecho_Anuncio PRIMARY KEY (ANUNCIO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

--PK tabla hecho pago_alquiler
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Pago_Alquiler')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler
	ADD CONSTRAINT PK_BI_Hecho_Pago_Alquiler PRIMARY KEY (PAGO_ALQUILER_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler agregada')
END
GO

/*PKs DIMENSIONES*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tiempo
	ADD CONSTRAINT PK_BI_Tiempo PRIMARY KEY (TIEMPO_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tiempo agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Ambiente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Ambiente
	ADD CONSTRAINT PK_BI_Ambiente PRIMARY KEY (AMBIENTE_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Ambiente agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Ubicacion
	ADD CONSTRAINT PK_BI_Ubicacion PRIMARY KEY (UBICACION_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Ubicacion agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Rango_Etario_Agente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente
	ADD CONSTRAINT PK_BI_Rango_Etario_Agente PRIMARY KEY (RANGO_ETARIO_AGENTE_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Rango_Etario_Inquilino')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino
	ADD CONSTRAINT PK_BI_Rango_Etario_Inquilino PRIMARY KEY (RANGO_ETARIO_INQUILINO_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Sucursal
	ADD CONSTRAINT PK_BI_Sucursal PRIMARY KEY (SUCURSAL_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Sucursal agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Rango_M2
	ADD CONSTRAINT PK_BI_Rango_M2 PRIMARY KEY (RANGO_M2_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Rango_M2 agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tipo_Inmueble
	ADD CONSTRAINT PK_BI_Tipo_Inmueble PRIMARY KEY (TIPO_INMUEBLE_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tipo_Inmueble agregada')
END
GO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tipo_Operacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tipo_Operacion
	ADD CONSTRAINT PK_BI_Tipo_Operacion PRIMARY KEY (TIPO_OPERACION_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tipo_Operacion agregada')
END
GO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tipo_Moneda
	ADD CONSTRAINT PK_BI_Tipo_Moneda PRIMARY KEY (TIPO_MONEDA_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tipo_Moneda agregada')
END
GO
