--FKs tabla hecho operacion
/*
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion
	ADD CONSTRAINT FK_BI_Hecho_Operacion_Tiempo FOREIGN KEY (OPERACION_TIEMPO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de TIEMPO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Operacion agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion
	ADD CONSTRAINT FK_BI_Hecho_Operacion_Tipo_Inmueble FOREIGN KEY (OPERACION_TIPO_INMUEBLE) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Inmueble(TIPO_INMUEBLE_ID)
	PRINT('Foreign key de TIPO_INMUEBLE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Operacion agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion
	ADD CONSTRAINT FK_BI_Hecho_Operacion_Rango_M2 FOREIGN KEY (OPERACION_RANGO_M2) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_M2(RANGO_M2_CODIGO)
	PRINT('Foreign key de RANGO_M2 de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Operacion agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion
	ADD CONSTRAINT FK_BI_Hecho_Operacion_Ubicacion FOREIGN KEY (OPERACION_UBICACION) REFERENCES GUISO_DE_LENTEJAS.BI_Ubicacion(UBICACION_CODIGO)
	PRINT('Foreign key de UBICACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Operacion agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tipo_Operacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion
	ADD CONSTRAINT FK_BI_Hecho_Operacion_Tipo_Operacion FOREIGN KEY (OPERACION_TIPO_OPERACION) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Operacion(TIPO_OPERACION_ID)
	PRINT('Foreign key de TIPO_OPERACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Operacion agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Rango_Etario')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion
	ADD CONSTRAINT FK_BI_Hecho_Operacion_Rango_Etario FOREIGN KEY (OPERACION_RANGO_ETARIO) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_Etario(RANGO_ETARIO_CODIGO)
	PRINT('Foreign key de RANGO_ETARIO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Operacion agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion
	ADD CONSTRAINT FK_BI_Hecho_Operacion_Sucursal FOREIGN KEY (OPERACION_SUCURSAL) REFERENCES GUISO_DE_LENTEJAS.BI_SUCURSAL(SUCURSAL_CODIGO)
	PRINT('Foreign key de SUCURSAL de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Operacion agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion
	ADD CONSTRAINT FK_BI_Hecho_Operacion_Ambientes FOREIGN KEY (OPERACION_AMBIENTES) REFERENCES GUISO_DE_LENTEJAS.BI_Ambiente(AMBIENTE_CODIGO)
	PRINT('Foreign key de AMBIENTES de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Operacion agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Operacion_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Operacion
	ADD CONSTRAINT FK_BI_Hecho_Operacion_Tipo_Moneda FOREIGN KEY (OPERACION_TIPO_MONEDA) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Moneda(TIPO_MONEDA_ID)
	PRINT('Foreign key de TIPO_MONEDA de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Operacion agregada')
END
GO
*/

--FKs tabla hecho anuncio
/*
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tiempo FOREIGN KEY (ANUNCIO_TIEMPO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de TIEMPO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Inmueble FOREIGN KEY (ANUNCIO_TIPO_INMUEBLE) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Inmueble(TIPO_INMUEBLE_ID)
	PRINT('Foreign key de TIPO_INMUEBLE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Rango_M2 FOREIGN KEY (ANUNCIO_RANGO_M2) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_M2(RANGO_M2_CODIGO)
	PRINT('Foreign key de RANGO_M2 de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Moneda FOREIGN KEY (ANUNCIO_TIPO_MONEDA) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Moneda(TIPO_MONEDA_ID)
	PRINT('Foreign key de TIPO_MONEDA de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Ubicacion FOREIGN KEY (ANUNCIO_UBICACION) REFERENCES GUISO_DE_LENTEJAS.BI_Ubicacion(UBICACION_CODIGO)
	PRINT('Foreign key de UBICACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Operacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Operacion FOREIGN KEY (ANUNCIO_TIPO_OPERACION) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Operacion(TIPO_OPERACION_ID)
	PRINT('Foreign key de TIPO_OPERACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Ambientes FOREIGN KEY (ANUNCIO_AMBIENTES) REFERENCES GUISO_DE_LENTEJAS.BI_Ambiente(AMBIENTE_CODIGO)
	PRINT('Foreign key de AMBIENTES de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO
*/