CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_DIMENSION_TIEMPO
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Tiempo (TIEMPO_ANIO, TIEMPO_CUATRIMESTRE, TIEMPO_MES, TIEMPO_DIA)
        SELECT DISTINCT YEAR(ANUNCIO_FECHA_PUBLICACION), CEILING(DATEPART(MONTH,ANUNCIO_FECHA_PUBLICACION)/4.00), MONTH(ANUNCIO_FECHA_PUBLICACION), DAY(ANUNCIO_FECHA_PUBLICACION) FROM GUISO_DE_LENTEJAS.ANUNCIO
        UNION
        SELECT DISTINCT YEAR(ANUNCIO_FECHA_FINALIZACION), CEILING(DATEPART(MONTH,ANUNCIO_FECHA_FINALIZACION)/4.00), MONTH(ANUNCIO_FECHA_FINALIZACION), DAY(ANUNCIO_FECHA_FINALIZACION) FROM GUISO_DE_LENTEJAS.ANUNCIO
        UNION
        SELECT DISTINCT YEAR(ALQUILER_FECHAINICIO), CEILING(DATEPART(MONTH,ALQUILER_FECHAINICIO)/4.00), MONTH(ALQUILER_FECHAINICIO), DAY(ALQUILER_FECHAINICIO) FROM GUISO_DE_LENTEJAS.ALQUILER
        UNION
        SELECT DISTINCT YEAR(ALQUILER_FECHAFIN), CEILING(DATEPART(MONTH,ALQUILER_FECHAFIN)/4.00), MONTH(ALQUILER_FECHAFIN), DAY(ALQUILER_FECHAFIN) FROM GUISO_DE_LENTEJAS.ALQUILER
        UNION
        SELECT DISTINCT YEAR(PAGO_ALQUILER_FECHA_VENCIMIENTO), CEILING(DATEPART(MONTH,PAGO_ALQUILER_FECHA_VENCIMIENTO)/4.00), MONTH(PAGO_ALQUILER_FECHA_VENCIMIENTO), DAY(PAGO_ALQUILER_FECHA_VENCIMIENTO) FROM GUISO_DE_LENTEJAS.PAGO_ALQUILER
        UNION
        SELECT DISTINCT YEAR(PAGO_ALQUILER_FECHA_PAGO), CEILING(DATEPART(MONTH,PAGO_ALQUILER_FECHA_PAGO)/4.00), MONTH(PAGO_ALQUILER_FECHA_PAGO), DAY(PAGO_ALQUILER_FECHA_PAGO) FROM GUISO_DE_LENTEJAS.PAGO_ALQUILER
        UNION
        SELECT DISTINCT YEAR(VENTA_FECHA), CEILING(DATEPART(MONTH,VENTA_FECHA)/4.00), MONTH(VENTA_FECHA), DAY(VENTA_FECHA) FROM GUISO_DE_LENTEJAS.VENTA
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_DIMENSION_TIEMPO ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_AGENTES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente (RANGO_ETARIO_AGENTE_DESCRIPCION)
        VALUES ('<25'), ('25-35'), ('35-50'), ('>50')
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_AGENTES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_INQUILINOS
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino (RANGO_ETARIO_INQUILINO_DESCRIPCION)
        VALUES ('<25'), ('25-35'), ('35-50'), ('>50')
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_INQUILINOS ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_INMUEBLES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Tipo_Inmueble (TIPO_INMUEBLE_DESCRIPCION)
        SELECT TIPO_INMUEBLE_DESCRIPCION FROM GUISO_DE_LENTEJAS.TIPO_INMUEBLE
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_INMUEBLES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_OPERACIONES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Tipo_Operacion (TIPO_OPERACION_DESCRIPCION)
        SELECT TIPO_OPERACION_DESCRIPCION FROM GUISO_DE_LENTEJAS.TIPO_OPERACION
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_OPERACIONES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_UBICACION
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Ubicacion (UBICACION_PROVINCIA, UBICACION_LOCALIDAD, UBICACION_BARRIO)
        SELECT p.PROVINCIA_NOMBRE , l.LOCALIDAD_NOMBRE , b.BARRIO_NOMBRE FROM GUISO_DE_LENTEJAS.BARRIO b INNER JOIN GUISO_DE_LENTEJAS.LOCALIDAD l ON l.LOCALIDAD_ID = b.BARRIO_LOCALIDAD INNER JOIN GUISO_DE_LENTEJAS.PROVINCIA p ON p.PROVINCIA_ID = l.LOCALIDAD_PROVINCIA
    END 
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_UBICACION ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_MONEDAS
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Tipo_Moneda (TIPO_MONEDA_DESCRIPCION)
        SELECT MONEDA_DESCRIPCION FROM GUISO_DE_LENTEJAS.MONEDA
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_MONEDAS ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_M2
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Rango_M2 (RANGO_M2_DESCRIPCION)
        VALUES ('<35'), ('35-55'), ('55-75'), ('75-100'),('>100')
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_M2 ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_SUCURSALES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Sucursal (SUCURSAL_NOMBRE)
        SELECT SUCURSAL_NOMBRE FROM GUISO_DE_LENTEJAS.SUCURSAL
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_SUCURSALES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_AMBIENTES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Ambiente (AMBIENTE_DESCRIPCION)
        SELECT AMBIENTE_DESCRIPCION FROM GUISO_DE_LENTEJAS.AMBIENTE
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_AMBIENTES ejecutado')
GO

CREATE FUNCTION GUISO_DE_LENTEJAS.rangoEtario_fx(@fecha_nac DATE)
RETURNS NVARCHAR(15)
AS
BEGIN
    DECLARE @rango NVARCHAR(15)
    DECLARE @edad INT

SELECT @edad = convert(int,DATEDIFF(YEAR,@fecha_nac, getdate()))


    SELECT @rango = CASE 
        WHEN @edad < 25  THEN '<25'
        WHEN @edad >= 25 AND @edad < 35 THEN '25-35'
        WHEN @edad >= 35 AND @edad <= 50 THEN '35-50'
        ELSE '>50'
        END

    RETURN @rango
END
GO

CREATE FUNCTION GUISO_DE_LENTEJAS.rangoM2_fx(@sup numeric(18,2))
RETURNS NVARCHAR(15)
AS
BEGIN
    DECLARE @rango NVARCHAR(15)

    SELECT @rango = CASE 
        WHEN @sup < 35  THEN '<35'
        WHEN @sup >= 35 AND @sup < 55 THEN '35-55'
        WHEN @sup >= 55 AND @sup <= 75 THEN '55-75'
        WHEN @sup >= 75 AND @sup <= 100 THEN '75-100'
        ELSE '>100'
    END

    RETURN @rango
END
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ANUNCIOS
AS
BEGIN
    
    INSERT INTO GUISO_DE_LENTEJAS.BI_Hecho_Anuncio (ANUNCIO_TIEMPO_INICIO, 
												    ANUNCIO_TIEMPO_FIN, 
												    ANUNCIO_TIPO_INMUEBLE,
												    ANUNCIO_RANGO_M2 ,
												    ANUNCIO_TIPO_MONEDA, 
												    ANUNCIO_UBICACION ,
												    ANUNCIO_TIPO_OPERACION ,
												    ANUNCIO_AMBIENTES,
												    ANUNCIO_PRECIO,
                                                    ANUNCIO_CANT_ANUNCIOS_AGRUPADOS)
    SELECT 
	    (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(a.ANUNCIO_FECHA_PUBLICACION) AND t.TIEMPO_MES = MONTH(a.ANUNCIO_FECHA_PUBLICACION) AND t.TIEMPO_DIA = DAY(a.ANUNCIO_FECHA_PUBLICACION)), 
	    (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(a.ANUNCIO_FECHA_FINALIZACION) AND t.TIEMPO_MES = MONTH(a.ANUNCIO_FECHA_FINALIZACION) AND t.TIEMPO_DIA = DAY(a.ANUNCIO_FECHA_FINALIZACION)),
	    (SELECT ti2.TIPO_INMUEBLE_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Inmueble ti2 WHERE ti2.TIPO_INMUEBLE_DESCRIPCION = ti.TIPO_INMUEBLE_DESCRIPCION),
	    (SELECT rm.RANGO_M2_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_M2 rm WHERE rm.RANGO_M2_DESCRIPCION = GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL)),
	    (SELECT m.TIPO_MONEDA_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Moneda m WHERE m.TIPO_MONEDA_DESCRIPCION = mo.MONEDA_DESCRIPCION),
	    (SELECT u.UBICACION_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ubicacion u WHERE u.UBICACION_PROVINCIA = pr.PROVINCIA_NOMBRE AND u.UBICACION_LOCALIDAD = lo.LOCALIDAD_NOMBRE AND u.UBICACION_BARRIO = ba.BARRIO_NOMBRE),
	    (SELECT tipoop.TIPO_OPERACION_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Operacion tipoop WHERE tipoop.TIPO_OPERACION_DESCRIPCION = tn.TIPO_OPERACION_DESCRIPCION),
	    (SELECT amb.AMBIENTE_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ambiente amb WHERE amb.AMBIENTE_DESCRIPCION = am.AMBIENTE_DESCRIPCION),
	    SUM(a.ANUNCIO_PRECIO_PUBLICADO),
        COUNT(*)
		    FROM GUISO_DE_LENTEJAS.ANUNCIO a
		    INNER JOIN GUISO_DE_LENTEJAS.INMUEBLE i ON i.INMUEBLE_NUMERO = a.ANUNCIO_INMUEBLE 
		    INNER JOIN GUISO_DE_LENTEJAS.TIPO_INMUEBLE ti ON ti.TIPO_INMUEBLE_ID = i.INMUEBLE_TIPOINMUEBLE
		    INNER JOIN GUISO_DE_LENTEJAS.MONEDA mo ON mo.MONEDA_ID = a.ANUNCIO_MONEDA
		    INNER JOIN GUISO_DE_LENTEJAS.BARRIO ba ON ba.BARRIO_ID = i.INMUEBLE_BARRIO 
		    INNER JOIN GUISO_DE_LENTEJAS.LOCALIDAD lo ON lo.LOCALIDAD_ID = ba.BARRIO_LOCALIDAD 
		    INNER JOIN GUISO_DE_LENTEJAS.PROVINCIA pr ON pr.PROVINCIA_ID = lo.LOCALIDAD_PROVINCIA 
		    INNER JOIN GUISO_DE_LENTEJAS.TIPO_OPERACION tn ON tn.TIPO_OPERACION_ID = a.ANUNCIO_TIPO_OPERACION
		    INNER JOIN GUISO_DE_LENTEJAS.AMBIENTE am ON am.AMBIENTE_ID = i.INMUEBLE_AMBIENTE
    GROUP BY a.ANUNCIO_FECHA_PUBLICACION , a.ANUNCIO_FECHA_FINALIZACION , ti.TIPO_INMUEBLE_DESCRIPCION , GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL), mo.MONEDA_DESCRIPCION , ba.BARRIO_NOMBRE , lo.LOCALIDAD_NOMBRE  , pr.PROVINCIA_NOMBRE  , tn.TIPO_OPERACION_DESCRIPCION , am.AMBIENTE_DESCRIPCION
END
PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ANUNCIOS ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_VENTAS
AS
BEGIN
    INSERT INTO GUISO_DE_LENTEJAS.BI_Hecho_Venta (VENTA_TIEMPO,
											VENTA_TIPO_INMUEBLE,
											VENTA_RANGO_M2,
											VENTA_UBICACION,
											VENTA_RANGO_ETARIO_AGENTE,
											VENTA_SUCURSAL,
											VENTA_AMBIENTES,
											VENTA_TIPO_MONEDA,
											VENTA_COMISION,
                                            VENTA_PRECIO,
                                            VENTA_CANT_VENTAS_AGRUPADAS)
    SELECT 
	    (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(v.VENTA_FECHA) AND t.TIEMPO_MES = MONTH(v.VENTA_FECHA) AND t.TIEMPO_DIA = DAY(v.VENTA_FECHA)),
	    (SELECT tipi.TIPO_INMUEBLE_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Inmueble tipi WHERE tipi.TIPO_INMUEBLE_DESCRIPCION = ti.TIPO_INMUEBLE_DESCRIPCION),
	    (SELECT rm.RANGO_M2_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_M2 rm WHERE rm.RANGO_M2_DESCRIPCION = GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL)),
	    (SELECT u.UBICACION_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ubicacion u WHERE u.UBICACION_PROVINCIA = pr.PROVINCIA_NOMBRE AND u.UBICACION_LOCALIDAD = lo.LOCALIDAD_NOMBRE AND u.UBICACION_BARRIO = ba.BARRIO_NOMBRE),
	    (SELECT rea.RANGO_ETARIO_AGENTE_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente rea WHERE rea.RANGO_ETARIO_AGENTE_DESCRIPCION = GUISO_DE_LENTEJAS.rangoEtario_fx(ai.AGENTE_INMOBILIARIO_FECHA_NACIMIENTO)),
	    (SELECT su.SUCURSAL_CODIGO FROM GUISO_DE_LENTEJAS.BI_Sucursal su WHERE su.SUCURSAL_NOMBRE = s.SUCURSAL_NOMBRE),
	    (SELECT amb.AMBIENTE_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ambiente amb WHERE amb.AMBIENTE_DESCRIPCION = am.AMBIENTE_DESCRIPCION),
	    (SELECT mon.TIPO_MONEDA_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Moneda mon WHERE mon.TIPO_MONEDA_DESCRIPCION = mo.MONEDA_DESCRIPCION),
	    SUM(v.VENTA_COMISION),
        SUM(v.VENTA_PRECIO),
        COUNT(*)
	    FROM GUISO_DE_LENTEJAS.VENTA v
	    INNER JOIN GUISO_DE_LENTEJAS.ANUNCIO a ON a.ANUNCIO_ID = v.VENTA_ANUNCIO 
	    INNER JOIN GUISO_DE_LENTEJAS.INMUEBLE i ON i.INMUEBLE_NUMERO = a.ANUNCIO_INMUEBLE
	    INNER JOIN GUISO_DE_LENTEJAS.TIPO_INMUEBLE ti ON ti.TIPO_INMUEBLE_ID = i.INMUEBLE_TIPOINMUEBLE
	    INNER JOIN GUISO_DE_LENTEJAS.BARRIO ba ON ba.BARRIO_ID = i.INMUEBLE_BARRIO 
	    INNER JOIN GUISO_DE_LENTEJAS.LOCALIDAD lo ON lo.LOCALIDAD_ID = ba.BARRIO_LOCALIDAD 
        INNER JOIN GUISO_DE_LENTEJAS.PROVINCIA pr ON pr.PROVINCIA_ID = lo.LOCALIDAD_PROVINCIA
        INNER JOIN GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO ai ON ai.AGENTE_INMOBILIARIO_ID = a.ANUNCIO_AGENTE_INMOBILIARIO 
        INNER JOIN GUISO_DE_LENTEJAS.SUCURSAL s ON s.SUCURSAL_ID = ai.AGENTE_INMOBILIARIO_SUCURSAL 
        INNER JOIN GUISO_DE_LENTEJAS.AMBIENTE am ON am.AMBIENTE_ID = i.INMUEBLE_AMBIENTE
	    INNER JOIN GUISO_DE_LENTEJAS.MONEDA mo ON mo.MONEDA_ID = v.VENTA_MONEDA
    GROUP BY v.VENTA_FECHA , ti.TIPO_INMUEBLE_DESCRIPCION , GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL), mo.MONEDA_DESCRIPCION ,  ba.BARRIO_NOMBRE , lo.LOCALIDAD_NOMBRE  , pr.PROVINCIA_NOMBRE , am.AMBIENTE_DESCRIPCION, s.SUCURSAL_NOMBRE, GUISO_DE_LENTEJAS.rangoEtario_fx(ai.AGENTE_INMOBILIARIO_FECHA_NACIMIENTO)
END
PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_VENTAS ejecutado')
GO

GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ALQUILERES
AS
BEGIN
    INSERT INTO GUISO_DE_LENTEJAS.BI_Hecho_Alquiler (ALQUILER_TIEMPO,
											ALQUILER_TIPO_INMUEBLE,
											ALQUILER_RANGO_M2,
											ALQUILER_UBICACION,
											ALQUILER_RANGO_ETARIO_AGENTE,
                                            ALQUILER_RANGO_ETARIO_INQUILINO,
											ALQUILER_SUCURSAL,
											ALQUILER_AMBIENTES,
											ALQUILER_TIPO_MONEDA,
											ALQUILER_COMISION,
                                            ALQUILER_CANT_ALQUILERES_AGRUPADOS)
    SELECT 
	    (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(a.ANUNCIO_FECHA_FINALIZACION) AND t.TIEMPO_MES = MONTH(a.ANUNCIO_FECHA_FINALIZACION) AND t.TIEMPO_DIA = DAY(a.ANUNCIO_FECHA_FINALIZACION)),
	    (SELECT tipi.TIPO_INMUEBLE_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Inmueble tipi WHERE tipi.TIPO_INMUEBLE_DESCRIPCION = ti.TIPO_INMUEBLE_DESCRIPCION),
	    (SELECT rm.RANGO_M2_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_M2 rm WHERE rm.RANGO_M2_DESCRIPCION = GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL)),
	    (SELECT u.UBICACION_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ubicacion u WHERE u.UBICACION_PROVINCIA = pr.PROVINCIA_NOMBRE AND u.UBICACION_LOCALIDAD = lo.LOCALIDAD_NOMBRE AND u.UBICACION_BARRIO = ba.BARRIO_NOMBRE),
	    (SELECT rea.RANGO_ETARIO_AGENTE_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente rea WHERE rea.RANGO_ETARIO_AGENTE_DESCRIPCION = GUISO_DE_LENTEJAS.rangoEtario_fx(ai.AGENTE_INMOBILIARIO_FECHA_NACIMIENTO)),
		(SELECT rei.RANGO_ETARIO_INQUILINO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino rei WHERE rei.RANGO_ETARIO_INQUILINO_DESCRIPCION = GUISO_DE_LENTEJAS.rangoEtario_fx(inq.INQUILINO_FECHA_NAC)),
	    (SELECT su.SUCURSAL_CODIGO FROM GUISO_DE_LENTEJAS.BI_Sucursal su WHERE su.SUCURSAL_NOMBRE = s.SUCURSAL_NOMBRE),
	    (SELECT amb.AMBIENTE_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ambiente amb WHERE amb.AMBIENTE_DESCRIPCION = am.AMBIENTE_DESCRIPCION),
	    (SELECT mon.TIPO_MONEDA_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Moneda mon WHERE mon.TIPO_MONEDA_DESCRIPCION = mo.MONEDA_DESCRIPCION),
	    SUM(alq.ALQUILER_COMISION),
        COUNT(*)
	    FROM GUISO_DE_LENTEJAS.ALQUILER alq
	    INNER JOIN GUISO_DE_LENTEJAS.ANUNCIO a ON a.ANUNCIO_ID = alq.ALQUILER_ANUNCIO 
	    INNER JOIN GUISO_DE_LENTEJAS.INMUEBLE i ON i.INMUEBLE_NUMERO = a.ANUNCIO_INMUEBLE
	    INNER JOIN GUISO_DE_LENTEJAS.TIPO_INMUEBLE ti ON ti.TIPO_INMUEBLE_ID = i.INMUEBLE_TIPOINMUEBLE
	    INNER JOIN GUISO_DE_LENTEJAS.BARRIO ba ON ba.BARRIO_ID = i.INMUEBLE_BARRIO 
	    INNER JOIN GUISO_DE_LENTEJAS.LOCALIDAD lo ON lo.LOCALIDAD_ID = ba.BARRIO_LOCALIDAD 
        INNER JOIN GUISO_DE_LENTEJAS.PROVINCIA pr ON pr.PROVINCIA_ID = lo.LOCALIDAD_PROVINCIA
        INNER JOIN GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO ai ON ai.AGENTE_INMOBILIARIO_ID = a.ANUNCIO_AGENTE_INMOBILIARIO 
        INNER JOIN GUISO_DE_LENTEJAS.SUCURSAL s ON s.SUCURSAL_ID = ai.AGENTE_INMOBILIARIO_SUCURSAL
		INNER JOIN GUISO_DE_LENTEJAS.INQUILINO inq ON inq.INQUILINO_ID = alq.ALQUILER_INQUILINO 
        INNER JOIN GUISO_DE_LENTEJAS.AMBIENTE am ON am.AMBIENTE_ID = i.INMUEBLE_AMBIENTE
	    INNER JOIN GUISO_DE_LENTEJAS.MONEDA mo ON mo.MONEDA_ID = a.ANUNCIO_MONEDA 
    GROUP BY a.ANUNCIO_FECHA_FINALIZACION , ti.TIPO_INMUEBLE_DESCRIPCION , GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL), mo.MONEDA_DESCRIPCION ,  ba.BARRIO_NOMBRE , lo.LOCALIDAD_NOMBRE  , pr.PROVINCIA_NOMBRE , am.AMBIENTE_DESCRIPCION, s.SUCURSAL_NOMBRE, GUISO_DE_LENTEJAS.rangoEtario_fx(ai.AGENTE_INMOBILIARIO_FECHA_NACIMIENTO), GUISO_DE_LENTEJAS.rangoEtario_fx(inq.INQUILINO_FECHA_NAC)
END
PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ALQUILERES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_PAGOS_ALQUILER
AS
BEGIN
    INSERT INTO GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler (PAGO_FECHA_PAGO, PAGO_FECHA_VENCIMIENTO,PAGO_CANT_PAGOS_AGRUPADOS)
        SELECT 
        (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(pa.PAGO_ALQUILER_FECHA_PAGO) AND t.TIEMPO_MES = MONTH(pa.PAGO_ALQUILER_FECHA_PAGO) AND t.TIEMPO_DIA = DAY(pa.PAGO_ALQUILER_FECHA_PAGO)),
        (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(pa.PAGO_ALQUILER_FECHA_VENCIMIENTO) AND t.TIEMPO_MES = MONTH(pa.PAGO_ALQUILER_FECHA_VENCIMIENTO) AND t.TIEMPO_DIA = DAY(pa.PAGO_ALQUILER_FECHA_VENCIMIENTO)),
        COUNT(*)           
        FROM GUISO_DE_LENTEJAS.PAGO_ALQUILER pa
    GROUP BY pa.PAGO_ALQUILER_FECHA_PAGO, pa.PAGO_ALQUILER_FECHA_VENCIMIENTO
END
PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_PAGOS_ALQUILER ejecutado')
GO

/*EJECUTAR*/
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_DIMENSION_TIEMPO
EXECUTE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_AGENTES
EXECUTE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_INQUILINOS
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_INMUEBLES
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_OPERACIONES
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_UBICACION
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_MONEDAS
EXECUTE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_M2
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_SUCURSALES
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_AMBIENTES
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ANUNCIOS
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_VENTAS
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ALQUILERES
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_PAGOS_ALQUILER

