--Vista 1: Duracion promedio en dias de publicacion de anuncios
CREATE VIEW GUISO_DE_LENTEJAS.BI_DURACION_PROMEDIO_PUBLICACION_ANUNCIO AS
    SELECT  tiop.TIPO_OPERACION_DESCRIPCION, 
            ub.UBICACION_BARRIO, 
            am.AMBIENTE_DESCRIPCION, 
            ti.TIEMPO_ANIO,
            ti.TIEMPO_CUATRIMESTRE, 
            SUM(DATEDIFF(DAY,DATEFROMPARTS(ti.TIEMPO_ANIO,ti.TIEMPO_MES, ti.TIEMPO_DIA), DATEFROMPARTS(ti2.TIEMPO_ANIO,ti2.TIEMPO_MES,ti2.TIEMPO_DIA))) / COUNT(*) AS 'Duracion Promedio de Publicacion (dias)'
            FROM GUISO_DE_LENTEJAS.BI_Hecho_Anuncio an
            JOIN GUISO_DE_LENTEJAS.BI_Tipo_Operacion tiop ON (tiop.TIPO_OPERACION_ID = an.ANUNCIO_TIPO_OPERACION)
            JOIN GUISO_DE_LENTEJAS.BI_Ambiente am ON (am.AMBIENTE_CODIGO = an.ANUNCIO_AMBIENTES)
            JOIN GUISO_DE_LENTEJAS.BI_Ubicacion ub ON (ub.UBICACION_CODIGO = an.ANUNCIO_UBICACION)
            JOIN GUISO_DE_LENTEJAS.BI_Tiempo ti ON (ti.TIEMPO_CODIGO = an.ANUNCIO_TIEMPO_INICIO)
            JOIN GUISO_DE_LENTEJAS.BI_Tiempo ti2 ON (ti2.TIEMPO_CODIGO = an.ANUNCIO_TIEMPO_FIN)
            GROUP BY tiop.TIPO_OPERACION_DESCRIPCION ,ub.UBICACION_BARRIO, am.AMBIENTE_DESCRIPCION,ti.TIEMPO_ANIO, ti.TIEMPO_CUATRIMESTRE
GO
