USE GD2C2023
GO

--Borrado de FKs tabla hecho venta
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Tiempo
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Tipo_Inmueble
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Rango_M2
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Ubicacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Rango_Etario_Agente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Rango_Etario_Agente
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Sucursal
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Ambientes
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Tipo_Moneda
END
GO

--Borrado de FKs tabla hecho alquiler
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Tiempo
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Tipo_Inmueble
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Rango_M2
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Ubicacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_Etario_Agente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Rango_Etario_Agente
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_Etario_Inquilino')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Rango_Etario_Inquilino
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Sucursal
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Ambientes
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Tipo_Moneda
END
GO

--Borrado de FKs tabla hecho anuncio
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tiempo_Inicio')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Tiempo_Inicio
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tiempo_Fin')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Tiempo_Fin
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Inmueble
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Rango_M2
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Moneda
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Ubicacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Operacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Operacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Ambientes
END
GO

--Borrado de FKs tabla hecho pago_alquiler
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Pago_Alquiler_Fecha_Pago')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler  DROP CONSTRAINT FK_BI_Hecho_Pago_Alquiler_Fecha_Pago
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Pago_Alquier_Fecha_Vencimiento')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler DROP CONSTRAINT FK_BI_Hecho_Pago_Alquier_Fecha_Vencimiento
END
GO

--Borrado de tablas de hechos

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Hecho_Venta', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Hecho_Alquiler', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Hecho_Anuncio', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler eliminada')
END
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Hecho_Venta') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta (
        VENTA_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        VENTA_TIEMPO numeric(18,0) NOT NULL,
        VENTA_TIPO_INMUEBLE numeric(18,0) NOT NULL,
        VENTA_RANGO_M2 numeric(18,0) NOT NULL,
        VENTA_UBICACION numeric(18,0) NOT NULL,
        VENTA_RANGO_ETARIO_AGENTE numeric(18,0) NOT NULL,
        VENTA_SUCURSAL numeric(18,0) NOT NULL,
        VENTA_AMBIENTES numeric(18,0) NOT NULL,
        VENTA_TIPO_MONEDA numeric(18,0) NOT NULL,
        VENTA_COMISION numeric(18,2) NOT NULL 
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Hecho_Alquiler') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler (
        ALQUILER_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        ALQUILER_TIEMPO numeric(18,0) NOT NULL,
        ALQUILER_TIPO_INMUEBLE numeric(18,0) NOT NULL,
        ALQUILER_RANGO_M2 numeric(18,0) NOT NULL,
        ALQUILER_UBICACION numeric(18,0) NOT NULL,
        ALQUILER_RANGO_ETARIO_AGENTE numeric(18,0) NOT NULL,
        ALQUILER_RANGO_ETARIO_INQUILINO numeric(18,0) NOT NULL,
        ALQUILER_SUCURSAL numeric(18,0) NOT NULL,
        ALQUILER_AMBIENTES numeric(18,0) NOT NULL,
        ALQUILER_TIPO_MONEDA numeric(18,0) NOT NULL,
        ALQUILER_COMISION numeric(18,2) NOT NULL 
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Hecho_Anuncio') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio (
        ANUNCIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        ANUNCIO_TIEMPO_INICIO numeric(18,0) NOT NULL,
        ANUNCIO_TIEMPO_FIN numeric(18,0) NOT NULL,
        ANUNCIO_TIPO_INMUEBLE numeric(18,0) NOT NULL,
        ANUNCIO_RANGO_M2 numeric(18,0) NOT NULL,
        ANUNCIO_TIPO_MONEDA numeric(18,0) NOT NULL,
        ANUNCIO_UBICACION numeric(18,0) NOT NULL,
        ANUNCIO_TIPO_OPERACION numeric(18,0) NOT NULL,
        ANUNCIO_AMBIENTES numeric(18,0) NOT NULL,
        ANUNCIO_PRECIO numeric(18,2) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Hecho_Pago_Alquiler') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler (
        PAGO_ALQUILER_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        PAGO_FECHA_PAGO numeric(18,0) NOT NULL,
        PAGO_FECHA_VENCIMIENTO numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler creada')
END
GO

--Creacion tablas dimensiones

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Tiempo') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Tiempo (
        TIEMPO_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        TIEMPO_ANIO numeric(18,0) NOT NULL,
        TIEMPO_CUATRIMESTRE numeric(18,0) NOT NULL,
        TIEMPO_MES numeric(18,0) NOT NULL,
        TIEMPO_DIA numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tiempo creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Ambiente') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Ambiente (
        AMBIENTE_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        AMBIENTE_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Ambiente creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Ubicacion') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Ubicacion (
        UBICACION_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        UBICACION_PROVINCIA nvarchar(100) NOT NULL,
        UBICACION_LOCALIDAD nvarchar(100) NOT NULL,
        UBICACION_BARRIO nvarchar(100) NOT NULL,
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Ubicacion creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Rango_Etario_Agente') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente (
        RANGO_ETARIO_AGENTE_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        RANGO_ETARIO_AGENTE_DESCRIPCION nvarchar(10) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Rango_Etario_Inquilino') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino (
        RANGO_ETARIO_INQUILINO_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        RANGO_ETARIO_INQUILINO_DESCRIPCION nvarchar(10) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Sucursal') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Sucursal (
        SUCURSAL_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        SUCURSAL_NOMBRE nvarchar(100) NOT NULL 
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Sucursal creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Rango_M2') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Rango_M2 (
        RANGO_M2_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        RANGO_M2_DESCRIPCION nvarchar(20) NOT NULL 
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Rango_M2 creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Tipo_Inmueble') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Tipo_Inmueble (
        TIPO_INMUEBLE_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        TIPO_INMUEBLE_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tipo_Inmueble creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Tipo_Operacion') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Tipo_Operacion (
        TIPO_OPERACION_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        TIPO_OPERACION_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tipo_Operacion creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Tipo_Moneda') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Tipo_Moneda (
        TIPO_MONEDA_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        TIPO_MONEDA_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tipo_Moneda creada')
END
GO
--PK tabla hecho venta
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Venta')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT PK_BI_Hecho_Venta PRIMARY KEY (VENTA_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

--PK tabla hecho alquiler
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Alquiler')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT PK_BI_Hecho_Alquiler PRIMARY KEY (ALQUILER_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

--PK tabla hecho anuncio
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Anuncio')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT PK_BI_Hecho_Anuncio PRIMARY KEY (ANUNCIO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

--PK tabla hecho pago_alquiler
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Pago_Alquiler')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler
	ADD CONSTRAINT PK_BI_Hecho_Pago_Alquiler PRIMARY KEY (PAGO_ALQUILER_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler agregada')
END
GO

/*PKs DIMENSIONES*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tiempo
	ADD CONSTRAINT PK_BI_Tiempo PRIMARY KEY (TIEMPO_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tiempo agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Ambiente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Ambiente
	ADD CONSTRAINT PK_BI_Ambiente PRIMARY KEY (AMBIENTE_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Ambiente agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Ubicacion
	ADD CONSTRAINT PK_BI_Ubicacion PRIMARY KEY (UBICACION_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Ubicacion agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Rango_Etario_Agente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente
	ADD CONSTRAINT PK_BI_Rango_Etario_Agente PRIMARY KEY (RANGO_ETARIO_AGENTE_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Rango_Etario_Inquilino')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino
	ADD CONSTRAINT PK_BI_Rango_Etario_Inquilino PRIMARY KEY (RANGO_ETARIO_INQUILINO_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Sucursal
	ADD CONSTRAINT PK_BI_Sucursal PRIMARY KEY (SUCURSAL_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Sucursal agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Rango_M2
	ADD CONSTRAINT PK_BI_Rango_M2 PRIMARY KEY (RANGO_M2_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Rango_M2 agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tipo_Inmueble
	ADD CONSTRAINT PK_BI_Tipo_Inmueble PRIMARY KEY (TIPO_INMUEBLE_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tipo_Inmueble agregada')
END
GO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tipo_Operacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tipo_Operacion
	ADD CONSTRAINT PK_BI_Tipo_Operacion PRIMARY KEY (TIPO_OPERACION_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tipo_Operacion agregada')
END
GO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tipo_Moneda
	ADD CONSTRAINT PK_BI_Tipo_Moneda PRIMARY KEY (TIPO_MONEDA_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tipo_Moneda agregada')
END
GO
--FKs tabla hecho venta

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Tiempo FOREIGN KEY (VENTA_TIEMPO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de TIEMPO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Tipo_Inmueble FOREIGN KEY (VENTA_TIPO_INMUEBLE) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Inmueble(TIPO_INMUEBLE_ID)
	PRINT('Foreign key de TIPO_INMUEBLE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Rango_M2 FOREIGN KEY (VENTA_RANGO_M2) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_M2(RANGO_M2_CODIGO)
	PRINT('Foreign key de RANGO_M2 de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Ubicacion FOREIGN KEY (VENTA_UBICACION) REFERENCES GUISO_DE_LENTEJAS.BI_Ubicacion(UBICACION_CODIGO)
	PRINT('Foreign key de UBICACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Rango_Etario_Agente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Rango_Etario_Agente FOREIGN KEY (VENTA_RANGO_ETARIO_AGENTE) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente(RANGO_ETARIO_AGENTE_CODIGO)
	PRINT('Foreign key de RANGO_ETARIO_AGENTE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Sucursal FOREIGN KEY (VENTA_SUCURSAL) REFERENCES GUISO_DE_LENTEJAS.BI_SUCURSAL(SUCURSAL_CODIGO)
	PRINT('Foreign key de SUCURSAL de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Ambientes FOREIGN KEY (VENTA_AMBIENTES) REFERENCES GUISO_DE_LENTEJAS.BI_Ambiente(AMBIENTE_CODIGO)
	PRINT('Foreign key de AMBIENTES de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Tipo_Moneda FOREIGN KEY (VENTA_TIPO_MONEDA) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Moneda(TIPO_MONEDA_ID)
	PRINT('Foreign key de TIPO_MONEDA de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

--FKs tabla hecho alquiler
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Tiempo FOREIGN KEY (ALQUILER_TIEMPO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de TIEMPO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Tipo_Inmueble FOREIGN KEY (ALQUILER_TIPO_INMUEBLE) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Inmueble(TIPO_INMUEBLE_ID)
	PRINT('Foreign key de TIPO_INMUEBLE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Rango_M2 FOREIGN KEY (ALQUILER_RANGO_M2) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_M2(RANGO_M2_CODIGO)
	PRINT('Foreign key de RANGO_M2 de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Ubicacion FOREIGN KEY (ALQUILER_UBICACION) REFERENCES GUISO_DE_LENTEJAS.BI_Ubicacion(UBICACION_CODIGO)
	PRINT('Foreign key de UBICACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_Etario_Agente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Rango_Etario_Agente FOREIGN KEY (ALQUILER_RANGO_ETARIO_AGENTE) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente(RANGO_ETARIO_AGENTE_CODIGO)
	PRINT('Foreign key de RANGO_ETARIO_AGENTE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_Etario_Inquilino')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Rango_Etario_Inquilino FOREIGN KEY (ALQUILER_RANGO_ETARIO_INQUILINO) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino(RANGO_ETARIO_INQUILINO_CODIGO)
	PRINT('Foreign key de RANGO_ETARIO_INQUILINO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Sucursal FOREIGN KEY (ALQUILER_SUCURSAL) REFERENCES GUISO_DE_LENTEJAS.BI_SUCURSAL(SUCURSAL_CODIGO)
	PRINT('Foreign key de SUCURSAL de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Ambientes FOREIGN KEY (ALQUILER_AMBIENTES) REFERENCES GUISO_DE_LENTEJAS.BI_Ambiente(AMBIENTE_CODIGO)
	PRINT('Foreign key de AMBIENTES de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Tipo_Moneda FOREIGN KEY (ALQUILER_TIPO_MONEDA) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Moneda(TIPO_MONEDA_ID)
	PRINT('Foreign key de TIPO_MONEDA de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO


--FKs tabla hecho anuncio
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tiempo_Inicio')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tiempo_Inicio FOREIGN KEY (ANUNCIO_TIEMPO_INICIO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de TIEMPO_INICIO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tiempo_Fin')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tiempo_Fin FOREIGN KEY (ANUNCIO_TIEMPO_FIN) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de TIEMPO_FIN de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Inmueble FOREIGN KEY (ANUNCIO_TIPO_INMUEBLE) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Inmueble(TIPO_INMUEBLE_ID)
	PRINT('Foreign key de TIPO_INMUEBLE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Rango_M2 FOREIGN KEY (ANUNCIO_RANGO_M2) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_M2(RANGO_M2_CODIGO)
	PRINT('Foreign key de RANGO_M2 de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Moneda FOREIGN KEY (ANUNCIO_TIPO_MONEDA) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Moneda(TIPO_MONEDA_ID)
	PRINT('Foreign key de TIPO_MONEDA de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Ubicacion FOREIGN KEY (ANUNCIO_UBICACION) REFERENCES GUISO_DE_LENTEJAS.BI_Ubicacion(UBICACION_CODIGO)
	PRINT('Foreign key de UBICACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Operacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Operacion FOREIGN KEY (ANUNCIO_TIPO_OPERACION) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Operacion(TIPO_OPERACION_ID)
	PRINT('Foreign key de TIPO_OPERACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Ambientes FOREIGN KEY (ANUNCIO_AMBIENTES) REFERENCES GUISO_DE_LENTEJAS.BI_Ambiente(AMBIENTE_CODIGO)
	PRINT('Foreign key de AMBIENTES de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

--FKs tabla hecho pago_alquiler
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Pago_Alquier_Fecha_Pago')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Pago_Alquier_Fecha_Pago FOREIGN KEY (PAGO_FECHA_PAGO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de FECHA_PAGO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Pago_Alquier_Fecha_Vencimiento')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Pago_Alquier_Fecha_Vencimiento FOREIGN KEY (PAGO_FECHA_VENCIMIENTO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de FECHA_VENCIMIENTO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler agregada')
END
GO--soy 9 vistas