USE GD2C2023
GO

--Borrado de FKs tabla hecho venta
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Tiempo
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Tipo_Inmueble
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Rango_M2
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Ubicacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Rango_Etario_Agente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Rango_Etario_Agente
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Sucursal
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Ambientes
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta DROP CONSTRAINT FK_BI_Hecho_Venta_Tipo_Moneda
END
GO

--Borrado de FKs tabla hecho alquiler
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Tiempo
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Tipo_Inmueble
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Rango_M2
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Ubicacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_Etario_Agente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Rango_Etario_Agente
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_Etario_Inquilino')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Rango_Etario_Inquilino
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Sucursal
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Ambientes
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler DROP CONSTRAINT FK_BI_Hecho_Alquiler_Tipo_Moneda
END
GO

--Borrado de FKs tabla hecho anuncio
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tiempo_Inicio')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Tiempo_Inicio
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tiempo_Fin')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Tiempo_Fin
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Inmueble
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Rango_M2
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Moneda
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Ubicacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Operacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Operacion
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio DROP CONSTRAINT FK_BI_Hecho_Anuncio_Ambientes
END
GO

--Borrado de FKs tabla hecho pago_alquiler
IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Pago_Alquier_Fecha_Pago')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler DROP CONSTRAINT FK_BI_Hecho_Pago_Alquier_Fecha_Pago
END
GO

IF EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
               WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Pago_Alquier_Fecha_Vencimiento')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler DROP CONSTRAINT FK_BI_Hecho_Pago_Alquier_Fecha_Vencimiento
END
GO

--Borrado de tablas de hechos

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Hecho_Venta', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Hecho_Alquiler', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Hecho_Anuncio', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Tiempo', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Tiempo
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tiempo eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Ambiente', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Ambiente
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Ambiente eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Ubicacion', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Ubicacion
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Ubicacion eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Sucursal', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Sucursal
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Sucursal eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Rango_M2', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Rango_M2
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Rango_M2 eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Tipo_Inmueble', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Tipo_Inmueble
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tipo_Inmueble eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Tipo_Operacion', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Tipo_Operacion
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tipo_Operacion eliminada')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_Tipo_Moneda', 'U') IS NOT NULL
BEGIN
	DROP TABLE GUISO_DE_LENTEJAS.BI_Tipo_Moneda
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tipo_Moneda eliminada')
END
/*BORRADO DE STORED PROCEDURES*/
IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_MIGRAR_DIMENSION_TIEMPO') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_DIMENSION_TIEMPO
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_DIMENSION_TIEMPO eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_AGENTES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_AGENTES
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_AGENTES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_INQUILINOS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_INQUILINOS
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_INQUILINOS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_INMUEBLES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_INMUEBLES
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_INMUEBLES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_OPERACIONES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_OPERACIONES
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_OPERACIONES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_MIGRAR_UBICACION') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_UBICACION
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_UBICACION eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_MONEDAS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_MONEDAS
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_MONEDAS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_M2') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_M2
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_M2 eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_MIGRAR_SUCURSALES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_SUCURSALES
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_SUCURSALES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_MIGRAR_AMBIENTES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_AMBIENTES
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_AMBIENTES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ANUNCIOS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ANUNCIOS
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ANUNCIOS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_VENTAS') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_VENTAS
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_VENTAS eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ALQUILERES') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ALQUILERES
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ALQUILERES eliminado')
END

IF OBJECT_ID('GUISO_DE_LENTEJAS.BI_MIGRAR_PAGOS_ALQUILER') IS NOT NULL
BEGIN
	DROP PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_PAGOS_ALQUILER
	PRINT('Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_PAGOS_ALQUILER eliminado')
END


IF EXISTS (select * from sys.objects where object_id = OBJECT_ID('GUISO_DE_LENTEJAS.rangoEtario_fx') and type = 'FN')
    DROP FUNCTION  GUISO_DE_LENTEJAS.rangoEtario_fx
GO

IF EXISTS (select * from sys.objects where object_id = OBJECT_ID('GUISO_DE_LENTEJAS.rangoM2_fx') and type = 'FN')
    DROP FUNCTION  GUISO_DE_LENTEJAS.rangoM2_fx
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Hecho_Venta') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta (
        VENTA_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        VENTA_TIEMPO numeric(18,0) NOT NULL,
        VENTA_TIPO_INMUEBLE numeric(18,0) NOT NULL,
        VENTA_RANGO_M2 numeric(18,0) NOT NULL,
        VENTA_UBICACION numeric(18,0) NOT NULL,
        VENTA_RANGO_ETARIO_AGENTE numeric(18,0) NOT NULL,
        VENTA_SUCURSAL numeric(18,0) NOT NULL,
        VENTA_AMBIENTES numeric(18,0) NOT NULL,
        VENTA_TIPO_MONEDA numeric(18,0) NOT NULL,
        VENTA_COMISION numeric(18,2) NOT NULL 
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Hecho_Alquiler') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler (
        ALQUILER_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        ALQUILER_TIEMPO numeric(18,0) NOT NULL,
        ALQUILER_TIPO_INMUEBLE numeric(18,0) NOT NULL,
        ALQUILER_RANGO_M2 numeric(18,0) NOT NULL,
        ALQUILER_UBICACION numeric(18,0) NOT NULL,
        ALQUILER_RANGO_ETARIO_AGENTE numeric(18,0) NOT NULL,
        ALQUILER_RANGO_ETARIO_INQUILINO numeric(18,0) NOT NULL,
        ALQUILER_SUCURSAL numeric(18,0) NOT NULL,
        ALQUILER_AMBIENTES numeric(18,0) NOT NULL,
        ALQUILER_TIPO_MONEDA numeric(18,0) NOT NULL,
        ALQUILER_COMISION numeric(18,2) NOT NULL 
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Hecho_Anuncio') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio (
        ANUNCIO_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        ANUNCIO_TIEMPO_INICIO numeric(18,0) NOT NULL,
        ANUNCIO_TIEMPO_FIN numeric(18,0) NOT NULL,
        ANUNCIO_TIPO_INMUEBLE numeric(18,0) NOT NULL,
        ANUNCIO_RANGO_M2 numeric(18,0) NOT NULL,
        ANUNCIO_TIPO_MONEDA numeric(18,0) NOT NULL,
        ANUNCIO_UBICACION numeric(18,0) NOT NULL,
        ANUNCIO_TIPO_OPERACION numeric(18,0) NOT NULL,
        ANUNCIO_AMBIENTES numeric(18,0) NOT NULL,
        ANUNCIO_PRECIO numeric(18,2) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio creada')
END
GO


IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Hecho_Pago_Alquiler') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler (
        PAGO_ALQUILER_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        PAGO_FECHA_PAGO numeric(18,0) NOT NULL,
        PAGO_FECHA_VENCIMIENTO numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler creada')
END
GO

--Creacion tablas dimensiones

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Tiempo') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Tiempo (
        TIEMPO_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        TIEMPO_ANIO numeric(18,0) NOT NULL,
        TIEMPO_CUATRIMESTRE numeric(18,0) NOT NULL,
        TIEMPO_MES numeric(18,0) NOT NULL,
        TIEMPO_DIA numeric(18,0) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tiempo creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Ambiente') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Ambiente (
        AMBIENTE_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        AMBIENTE_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Ambiente creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Ubicacion') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Ubicacion (
        UBICACION_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        UBICACION_PROVINCIA nvarchar(100) NOT NULL,
        UBICACION_LOCALIDAD nvarchar(100) NOT NULL,
        UBICACION_BARRIO nvarchar(100) NOT NULL,
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Ubicacion creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Rango_Etario_Agente') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente (
        RANGO_ETARIO_AGENTE_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        RANGO_ETARIO_AGENTE_DESCRIPCION nvarchar(10) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Rango_Etario_Inquilino') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino (
        RANGO_ETARIO_INQUILINO_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        RANGO_ETARIO_INQUILINO_DESCRIPCION nvarchar(10) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Sucursal') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Sucursal (
        SUCURSAL_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        SUCURSAL_NOMBRE nvarchar(100) NOT NULL 
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Sucursal creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Rango_M2') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Rango_M2 (
        RANGO_M2_CODIGO numeric(18,0) NOT NULL IDENTITY(1,1),
        RANGO_M2_DESCRIPCION nvarchar(20) NOT NULL 
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Rango_M2 creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Tipo_Inmueble') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Tipo_Inmueble (
        TIPO_INMUEBLE_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        TIPO_INMUEBLE_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tipo_Inmueble creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Tipo_Operacion') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Tipo_Operacion (
        TIPO_OPERACION_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        TIPO_OPERACION_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tipo_Operacion creada')
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id= OBJECT_ID(N'[GUISO_DE_LENTEJAS].BI_Tipo_Moneda') AND type = 'U')
BEGIN
	CREATE TABLE GUISO_DE_LENTEJAS.BI_Tipo_Moneda (
        TIPO_MONEDA_ID numeric(18,0) NOT NULL IDENTITY(1,1),
        TIPO_MONEDA_DESCRIPCION nvarchar(100) NOT NULL
	)
	PRINT('Tabla GUISO_DE_LENTEJAS.BI_Tipo_Moneda creada')
END
GO
--PK tabla hecho venta
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Venta')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT PK_BI_Hecho_Venta PRIMARY KEY (VENTA_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

--PK tabla hecho alquiler
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Alquiler')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT PK_BI_Hecho_Alquiler PRIMARY KEY (ALQUILER_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

--PK tabla hecho anuncio
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Anuncio')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT PK_BI_Hecho_Anuncio PRIMARY KEY (ANUNCIO_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

--PK tabla hecho pago_alquiler
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Hecho_Pago_Alquiler')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler
	ADD CONSTRAINT PK_BI_Hecho_Pago_Alquiler PRIMARY KEY (PAGO_ALQUILER_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler agregada')
END
GO

/*PKs DIMENSIONES*/
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tiempo
	ADD CONSTRAINT PK_BI_Tiempo PRIMARY KEY (TIEMPO_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tiempo agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Ambiente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Ambiente
	ADD CONSTRAINT PK_BI_Ambiente PRIMARY KEY (AMBIENTE_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Ambiente agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Ubicacion
	ADD CONSTRAINT PK_BI_Ubicacion PRIMARY KEY (UBICACION_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Ubicacion agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Rango_Etario_Agente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente
	ADD CONSTRAINT PK_BI_Rango_Etario_Agente PRIMARY KEY (RANGO_ETARIO_AGENTE_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Rango_Etario_Inquilino')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino
	ADD CONSTRAINT PK_BI_Rango_Etario_Inquilino PRIMARY KEY (RANGO_ETARIO_INQUILINO_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Sucursal
	ADD CONSTRAINT PK_BI_Sucursal PRIMARY KEY (SUCURSAL_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Sucursal agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Rango_M2
	ADD CONSTRAINT PK_BI_Rango_M2 PRIMARY KEY (RANGO_M2_CODIGO)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Rango_M2 agregada')
END
GO

IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tipo_Inmueble
	ADD CONSTRAINT PK_BI_Tipo_Inmueble PRIMARY KEY (TIPO_INMUEBLE_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tipo_Inmueble agregada')
END
GO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tipo_Operacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tipo_Operacion
	ADD CONSTRAINT PK_BI_Tipo_Operacion PRIMARY KEY (TIPO_OPERACION_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tipo_Operacion agregada')
END
GO
IF NOT EXISTS (SELECT * 
    		   FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME ='PK_BI_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Tipo_Moneda
	ADD CONSTRAINT PK_BI_Tipo_Moneda PRIMARY KEY (TIPO_MONEDA_ID)
	PRINT('Primary key de la tabla GUISO_DE_LENTEJAS.BI_Tipo_Moneda agregada')
END
GO
--FKs tabla hecho venta

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Tiempo FOREIGN KEY (VENTA_TIEMPO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de TIEMPO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Tipo_Inmueble FOREIGN KEY (VENTA_TIPO_INMUEBLE) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Inmueble(TIPO_INMUEBLE_ID)
	PRINT('Foreign key de TIPO_INMUEBLE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Rango_M2 FOREIGN KEY (VENTA_RANGO_M2) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_M2(RANGO_M2_CODIGO)
	PRINT('Foreign key de RANGO_M2 de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Ubicacion FOREIGN KEY (VENTA_UBICACION) REFERENCES GUISO_DE_LENTEJAS.BI_Ubicacion(UBICACION_CODIGO)
	PRINT('Foreign key de UBICACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Rango_Etario_Agente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Rango_Etario_Agente FOREIGN KEY (VENTA_RANGO_ETARIO_AGENTE) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente(RANGO_ETARIO_AGENTE_CODIGO)
	PRINT('Foreign key de RANGO_ETARIO_AGENTE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Sucursal FOREIGN KEY (VENTA_SUCURSAL) REFERENCES GUISO_DE_LENTEJAS.BI_SUCURSAL(SUCURSAL_CODIGO)
	PRINT('Foreign key de SUCURSAL de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Ambientes FOREIGN KEY (VENTA_AMBIENTES) REFERENCES GUISO_DE_LENTEJAS.BI_Ambiente(AMBIENTE_CODIGO)
	PRINT('Foreign key de AMBIENTES de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Venta_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Venta
	ADD CONSTRAINT FK_BI_Hecho_Venta_Tipo_Moneda FOREIGN KEY (VENTA_TIPO_MONEDA) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Moneda(TIPO_MONEDA_ID)
	PRINT('Foreign key de TIPO_MONEDA de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Venta agregada')
END
GO

--FKs tabla hecho alquiler
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tiempo')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Tiempo FOREIGN KEY (ALQUILER_TIEMPO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de TIEMPO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Tipo_Inmueble FOREIGN KEY (ALQUILER_TIPO_INMUEBLE) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Inmueble(TIPO_INMUEBLE_ID)
	PRINT('Foreign key de TIPO_INMUEBLE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Rango_M2 FOREIGN KEY (ALQUILER_RANGO_M2) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_M2(RANGO_M2_CODIGO)
	PRINT('Foreign key de RANGO_M2 de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Ubicacion FOREIGN KEY (ALQUILER_UBICACION) REFERENCES GUISO_DE_LENTEJAS.BI_Ubicacion(UBICACION_CODIGO)
	PRINT('Foreign key de UBICACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_Etario_Agente')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Rango_Etario_Agente FOREIGN KEY (ALQUILER_RANGO_ETARIO_AGENTE) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente(RANGO_ETARIO_AGENTE_CODIGO)
	PRINT('Foreign key de RANGO_ETARIO_AGENTE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Rango_Etario_Inquilino')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Rango_Etario_Inquilino FOREIGN KEY (ALQUILER_RANGO_ETARIO_INQUILINO) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino(RANGO_ETARIO_INQUILINO_CODIGO)
	PRINT('Foreign key de RANGO_ETARIO_INQUILINO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Sucursal')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Sucursal FOREIGN KEY (ALQUILER_SUCURSAL) REFERENCES GUISO_DE_LENTEJAS.BI_SUCURSAL(SUCURSAL_CODIGO)
	PRINT('Foreign key de SUCURSAL de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Ambientes FOREIGN KEY (ALQUILER_AMBIENTES) REFERENCES GUISO_DE_LENTEJAS.BI_Ambiente(AMBIENTE_CODIGO)
	PRINT('Foreign key de AMBIENTES de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Alquiler_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Alquiler_Tipo_Moneda FOREIGN KEY (ALQUILER_TIPO_MONEDA) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Moneda(TIPO_MONEDA_ID)
	PRINT('Foreign key de TIPO_MONEDA de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Alquiler agregada')
END
GO


--FKs tabla hecho anuncio
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tiempo_Inicio')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tiempo_Inicio FOREIGN KEY (ANUNCIO_TIEMPO_INICIO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de TIEMPO_INICIO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tiempo_Fin')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tiempo_Fin FOREIGN KEY (ANUNCIO_TIEMPO_FIN) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de TIEMPO_FIN de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Inmueble')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Inmueble FOREIGN KEY (ANUNCIO_TIPO_INMUEBLE) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Inmueble(TIPO_INMUEBLE_ID)
	PRINT('Foreign key de TIPO_INMUEBLE de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Rango_M2')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Rango_M2 FOREIGN KEY (ANUNCIO_RANGO_M2) REFERENCES GUISO_DE_LENTEJAS.BI_Rango_M2(RANGO_M2_CODIGO)
	PRINT('Foreign key de RANGO_M2 de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Moneda')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Moneda FOREIGN KEY (ANUNCIO_TIPO_MONEDA) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Moneda(TIPO_MONEDA_ID)
	PRINT('Foreign key de TIPO_MONEDA de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Ubicacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Ubicacion FOREIGN KEY (ANUNCIO_UBICACION) REFERENCES GUISO_DE_LENTEJAS.BI_Ubicacion(UBICACION_CODIGO)
	PRINT('Foreign key de UBICACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Tipo_Operacion')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Tipo_Operacion FOREIGN KEY (ANUNCIO_TIPO_OPERACION) REFERENCES GUISO_DE_LENTEJAS.BI_Tipo_Operacion(TIPO_OPERACION_ID)
	PRINT('Foreign key de TIPO_OPERACION de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Anuncio_Ambientes')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Anuncio
	ADD CONSTRAINT FK_BI_Hecho_Anuncio_Ambientes FOREIGN KEY (ANUNCIO_AMBIENTES) REFERENCES GUISO_DE_LENTEJAS.BI_Ambiente(AMBIENTE_CODIGO)
	PRINT('Foreign key de AMBIENTES de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Anuncio agregada')
END
GO

--FKs tabla hecho pago_alquiler
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Pago_Alquier_Fecha_Pago')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Pago_Alquier_Fecha_Pago FOREIGN KEY (PAGO_FECHA_PAGO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de FECHA_PAGO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler agregada')
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
				WHERE CONSTRAINT_NAME ='FK_BI_Hecho_Pago_Alquier_Fecha_Vencimiento')
BEGIN
	ALTER TABLE GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler
	ADD CONSTRAINT FK_BI_Hecho_Pago_Alquier_Fecha_Vencimiento FOREIGN KEY (PAGO_FECHA_VENCIMIENTO) REFERENCES GUISO_DE_LENTEJAS.BI_Tiempo(TIEMPO_CODIGO)
	PRINT('Foreign key de FECHA_VENCIMIENTO de la tabla GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler agregada')
END
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_DIMENSION_TIEMPO
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Tiempo (TIEMPO_ANIO, TIEMPO_CUATRIMESTRE, TIEMPO_MES, TIEMPO_DIA)
        SELECT DISTINCT YEAR(ANUNCIO_FECHA_PUBLICACION), CEILING(DATEPART(MONTH,ANUNCIO_FECHA_PUBLICACION)/4.00), MONTH(ANUNCIO_FECHA_PUBLICACION), DAY(ANUNCIO_FECHA_PUBLICACION) FROM GUISO_DE_LENTEJAS.ANUNCIO
        UNION
        SELECT DISTINCT YEAR(ANUNCIO_FECHA_FINALIZACION), CEILING(DATEPART(MONTH,ANUNCIO_FECHA_FINALIZACION)/4.00), MONTH(ANUNCIO_FECHA_FINALIZACION), DAY(ANUNCIO_FECHA_FINALIZACION) FROM GUISO_DE_LENTEJAS.ANUNCIO
        UNION
        SELECT DISTINCT YEAR(ALQUILER_FECHAINICIO), CEILING(DATEPART(MONTH,ALQUILER_FECHAINICIO)/4.00), MONTH(ALQUILER_FECHAINICIO), DAY(ALQUILER_FECHAINICIO) FROM GUISO_DE_LENTEJAS.ALQUILER
        UNION
        SELECT DISTINCT YEAR(ALQUILER_FECHAFIN), CEILING(DATEPART(MONTH,ALQUILER_FECHAFIN)/4.00), MONTH(ALQUILER_FECHAFIN), DAY(ALQUILER_FECHAFIN) FROM GUISO_DE_LENTEJAS.ALQUILER
        UNION
        SELECT DISTINCT YEAR(PAGO_ALQUILER_FECHA_VENCIMIENTO), CEILING(DATEPART(MONTH,PAGO_ALQUILER_FECHA_VENCIMIENTO)/4.00), MONTH(PAGO_ALQUILER_FECHA_VENCIMIENTO), DAY(PAGO_ALQUILER_FECHA_VENCIMIENTO) FROM GUISO_DE_LENTEJAS.PAGO_ALQUILER
        UNION
        SELECT DISTINCT YEAR(PAGO_ALQUILER_FECHA_PAGO), CEILING(DATEPART(MONTH,PAGO_ALQUILER_FECHA_PAGO)/4.00), MONTH(PAGO_ALQUILER_FECHA_PAGO), DAY(PAGO_ALQUILER_FECHA_PAGO) FROM GUISO_DE_LENTEJAS.PAGO_ALQUILER
        UNION
        SELECT DISTINCT YEAR(VENTA_FECHA), CEILING(DATEPART(MONTH,VENTA_FECHA)/4.00), MONTH(VENTA_FECHA), DAY(VENTA_FECHA) FROM GUISO_DE_LENTEJAS.VENTA
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_DIMENSION_TIEMPO ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_AGENTES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente (RANGO_ETARIO_AGENTE_DESCRIPCION)
        VALUES ('<25'), ('25-35'), ('35-50'), ('>50')
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_AGENTES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_INQUILINOS
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino (RANGO_ETARIO_INQUILINO_DESCRIPCION)
        VALUES ('<25'), ('25-35'), ('35-50'), ('>50')
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_INQUILINOS ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_INMUEBLES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Tipo_Inmueble (TIPO_INMUEBLE_DESCRIPCION)
        SELECT TIPO_INMUEBLE_DESCRIPCION FROM GUISO_DE_LENTEJAS.TIPO_INMUEBLE
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_INMUEBLES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_OPERACIONES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Tipo_Operacion (TIPO_OPERACION_DESCRIPCION)
        SELECT TIPO_OPERACION_DESCRIPCION FROM GUISO_DE_LENTEJAS.TIPO_OPERACION
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_OPERACIONES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_UBICACION
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Ubicacion (UBICACION_PROVINCIA, UBICACION_LOCALIDAD, UBICACION_BARRIO)
        SELECT p.PROVINCIA_NOMBRE , l.LOCALIDAD_NOMBRE , b.BARRIO_NOMBRE FROM GUISO_DE_LENTEJAS.BARRIO b INNER JOIN GUISO_DE_LENTEJAS.LOCALIDAD l ON l.LOCALIDAD_ID = b.BARRIO_LOCALIDAD INNER JOIN GUISO_DE_LENTEJAS.PROVINCIA p ON p.PROVINCIA_ID = l.LOCALIDAD_PROVINCIA
    END 
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_UBICACION ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_MONEDAS
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Tipo_Moneda (TIPO_MONEDA_DESCRIPCION)
        SELECT MONEDA_DESCRIPCION FROM GUISO_DE_LENTEJAS.MONEDA
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_MONEDAS ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_M2
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Rango_M2 (RANGO_M2_DESCRIPCION)
        VALUES ('<35'), ('35-55'), ('55-75'), ('75-100'),('>100')
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_M2 ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_SUCURSALES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Sucursal (SUCURSAL_NOMBRE)
        SELECT SUCURSAL_NOMBRE FROM GUISO_DE_LENTEJAS.SUCURSAL
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_SUCURSALES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_AMBIENTES
AS
    BEGIN
        INSERT INTO GUISO_DE_LENTEJAS.BI_Ambiente (AMBIENTE_DESCRIPCION)
        SELECT AMBIENTE_DESCRIPCION FROM GUISO_DE_LENTEJAS.AMBIENTE
    END
    PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_AMBIENTES ejecutado')
GO

CREATE FUNCTION GUISO_DE_LENTEJAS.rangoEtario_fx(@fecha_nac DATE)
RETURNS NVARCHAR(15)
AS
BEGIN
    DECLARE @rango NVARCHAR(15)
    DECLARE @edad INT

SELECT @edad = convert(int,DATEDIFF(YEAR,@fecha_nac, getdate()))


    SELECT @rango = CASE 
        WHEN @edad < 25  THEN '<25'
        WHEN @edad >= 25 AND @edad < 35 THEN '25-35'
        WHEN @edad >= 35 AND @edad <= 50 THEN '35-50'
        ELSE '>50'
        END

    RETURN @rango
END
GO

CREATE FUNCTION GUISO_DE_LENTEJAS.rangoM2_fx(@sup numeric(18,2))
RETURNS NVARCHAR(15)
AS
BEGIN
    DECLARE @rango NVARCHAR(15)

    SELECT @rango = CASE 
        WHEN @sup < 35  THEN '<35'
        WHEN @sup >= 35 AND @sup < 55 THEN '35-55'
        WHEN @sup >= 55 AND @sup <= 75 THEN '55-75'
        WHEN @sup >= 75 AND @sup <= 100 THEN '75-100'
        ELSE '>100'
    END

    RETURN @rango
END
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ANUNCIOS
AS
BEGIN
    
    INSERT INTO GUISO_DE_LENTEJAS.BI_Hecho_Anuncio (ANUNCIO_TIEMPO_INICIO, 
												    ANUNCIO_TIEMPO_FIN, 
												    ANUNCIO_TIPO_INMUEBLE,
												    ANUNCIO_RANGO_M2 ,
												    ANUNCIO_TIPO_MONEDA, 
												    ANUNCIO_UBICACION ,
												    ANUNCIO_TIPO_OPERACION ,
												    ANUNCIO_AMBIENTES,
												    ANUNCIO_PRECIO)
    SELECT 
	    (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(a.ANUNCIO_FECHA_PUBLICACION) AND t.TIEMPO_MES = MONTH(a.ANUNCIO_FECHA_PUBLICACION) AND t.TIEMPO_DIA = DAY(a.ANUNCIO_FECHA_PUBLICACION)), 
	    (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(a.ANUNCIO_FECHA_FINALIZACION) AND t.TIEMPO_MES = MONTH(a.ANUNCIO_FECHA_FINALIZACION) AND t.TIEMPO_DIA = DAY(a.ANUNCIO_FECHA_FINALIZACION)),
	    (SELECT ti2.TIPO_INMUEBLE_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Inmueble ti2 WHERE ti2.TIPO_INMUEBLE_DESCRIPCION = ti.TIPO_INMUEBLE_DESCRIPCION),
	    (SELECT rm.RANGO_M2_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_M2 rm WHERE rm.RANGO_M2_DESCRIPCION = GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL)),
	    (SELECT m.TIPO_MONEDA_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Moneda m WHERE m.TIPO_MONEDA_DESCRIPCION = mo.MONEDA_DESCRIPCION),
	    (SELECT u.UBICACION_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ubicacion u WHERE u.UBICACION_PROVINCIA = pr.PROVINCIA_NOMBRE AND u.UBICACION_LOCALIDAD = lo.LOCALIDAD_NOMBRE AND u.UBICACION_BARRIO = ba.BARRIO_NOMBRE),
	    (SELECT tipoop.TIPO_OPERACION_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Operacion tipoop WHERE tipoop.TIPO_OPERACION_DESCRIPCION = tn.TIPO_OPERACION_DESCRIPCION),
	    (SELECT amb.AMBIENTE_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ambiente amb WHERE amb.AMBIENTE_DESCRIPCION = am.AMBIENTE_DESCRIPCION),
	    SUM(a.ANUNCIO_PRECIO_PUBLICADO)
		    FROM GUISO_DE_LENTEJAS.ANUNCIO a
		    INNER JOIN GUISO_DE_LENTEJAS.INMUEBLE i ON i.INMUEBLE_NUMERO = a.ANUNCIO_INMUEBLE 
		    INNER JOIN GUISO_DE_LENTEJAS.TIPO_INMUEBLE ti ON ti.TIPO_INMUEBLE_ID = i.INMUEBLE_TIPOINMUEBLE
		    INNER JOIN GUISO_DE_LENTEJAS.MONEDA mo ON mo.MONEDA_ID = a.ANUNCIO_MONEDA
		    INNER JOIN GUISO_DE_LENTEJAS.BARRIO ba ON ba.BARRIO_ID = i.INMUEBLE_BARRIO 
		    INNER JOIN GUISO_DE_LENTEJAS.LOCALIDAD lo ON lo.LOCALIDAD_ID = ba.BARRIO_LOCALIDAD 
		    INNER JOIN GUISO_DE_LENTEJAS.PROVINCIA pr ON pr.PROVINCIA_ID = lo.LOCALIDAD_PROVINCIA 
		    INNER JOIN GUISO_DE_LENTEJAS.TIPO_OPERACION tn ON tn.TIPO_OPERACION_ID = a.ANUNCIO_TIPO_OPERACION
		    INNER JOIN GUISO_DE_LENTEJAS.AMBIENTE am ON am.AMBIENTE_ID = i.INMUEBLE_AMBIENTE
    GROUP BY a.ANUNCIO_FECHA_PUBLICACION , a.ANUNCIO_FECHA_FINALIZACION , ti.TIPO_INMUEBLE_DESCRIPCION , GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL), mo.MONEDA_DESCRIPCION , ba.BARRIO_NOMBRE , lo.LOCALIDAD_NOMBRE  , pr.PROVINCIA_NOMBRE  , tn.TIPO_OPERACION_DESCRIPCION , am.AMBIENTE_DESCRIPCION
END
PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ANUNCIOS ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_VENTAS
AS
BEGIN
    INSERT INTO GUISO_DE_LENTEJAS.BI_Hecho_Venta (VENTA_TIEMPO,
											VENTA_TIPO_INMUEBLE,
											VENTA_RANGO_M2,
											VENTA_UBICACION,
											VENTA_RANGO_ETARIO_AGENTE,
											VENTA_SUCURSAL,
											VENTA_AMBIENTES,
											VENTA_TIPO_MONEDA,
											VENTA_COMISION)
    SELECT 
	    (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(v.VENTA_FECHA) AND t.TIEMPO_MES = MONTH(v.VENTA_FECHA) AND t.TIEMPO_DIA = DAY(v.VENTA_FECHA)),
	    (SELECT tipi.TIPO_INMUEBLE_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Inmueble tipi WHERE tipi.TIPO_INMUEBLE_DESCRIPCION = ti.TIPO_INMUEBLE_DESCRIPCION),
	    (SELECT rm.RANGO_M2_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_M2 rm WHERE rm.RANGO_M2_DESCRIPCION = GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL)),
	    (SELECT u.UBICACION_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ubicacion u WHERE u.UBICACION_PROVINCIA = pr.PROVINCIA_NOMBRE AND u.UBICACION_LOCALIDAD = lo.LOCALIDAD_NOMBRE AND u.UBICACION_BARRIO = ba.BARRIO_NOMBRE),
	    (SELECT rea.RANGO_ETARIO_AGENTE_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente rea WHERE rea.RANGO_ETARIO_AGENTE_DESCRIPCION = GUISO_DE_LENTEJAS.rangoEtario_fx(ai.AGENTE_INMOBILIARIO_FECHA_NACIMIENTO)),
	    (SELECT su.SUCURSAL_CODIGO FROM GUISO_DE_LENTEJAS.BI_Sucursal su WHERE su.SUCURSAL_NOMBRE = s.SUCURSAL_NOMBRE),
	    (SELECT amb.AMBIENTE_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ambiente amb WHERE amb.AMBIENTE_DESCRIPCION = am.AMBIENTE_DESCRIPCION),
	    (SELECT mon.TIPO_MONEDA_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Moneda mon WHERE mon.TIPO_MONEDA_DESCRIPCION = mo.MONEDA_DESCRIPCION),
	    SUM(v.VENTA_COMISION)
	    FROM GUISO_DE_LENTEJAS.VENTA v
	    INNER JOIN GUISO_DE_LENTEJAS.ANUNCIO a ON a.ANUNCIO_ID = v.VENTA_ANUNCIO 
	    INNER JOIN GUISO_DE_LENTEJAS.INMUEBLE i ON i.INMUEBLE_NUMERO = a.ANUNCIO_INMUEBLE
	    INNER JOIN GUISO_DE_LENTEJAS.TIPO_INMUEBLE ti ON ti.TIPO_INMUEBLE_ID = i.INMUEBLE_TIPOINMUEBLE
	    INNER JOIN GUISO_DE_LENTEJAS.BARRIO ba ON ba.BARRIO_ID = i.INMUEBLE_BARRIO 
	    INNER JOIN GUISO_DE_LENTEJAS.LOCALIDAD lo ON lo.LOCALIDAD_ID = ba.BARRIO_LOCALIDAD 
        INNER JOIN GUISO_DE_LENTEJAS.PROVINCIA pr ON pr.PROVINCIA_ID = lo.LOCALIDAD_PROVINCIA
        INNER JOIN GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO ai ON ai.AGENTE_INMOBILIARIO_ID = a.ANUNCIO_AGENTE_INMOBILIARIO 
        INNER JOIN GUISO_DE_LENTEJAS.SUCURSAL s ON s.SUCURSAL_ID = ai.AGENTE_INMOBILIARIO_SUCURSAL 
        INNER JOIN GUISO_DE_LENTEJAS.AMBIENTE am ON am.AMBIENTE_ID = i.INMUEBLE_AMBIENTE
	    INNER JOIN GUISO_DE_LENTEJAS.MONEDA mo ON mo.MONEDA_ID = v.VENTA_MONEDA
    GROUP BY v.VENTA_FECHA , ti.TIPO_INMUEBLE_DESCRIPCION , GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL), mo.MONEDA_DESCRIPCION ,  ba.BARRIO_NOMBRE , lo.LOCALIDAD_NOMBRE  , pr.PROVINCIA_NOMBRE , am.AMBIENTE_DESCRIPCION, s.SUCURSAL_NOMBRE, GUISO_DE_LENTEJAS.rangoEtario_fx(ai.AGENTE_INMOBILIARIO_FECHA_NACIMIENTO)
END
PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_VENTAS ejecutado')
GO

GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ALQUILERES
AS
BEGIN
    INSERT INTO GUISO_DE_LENTEJAS.BI_Hecho_Alquiler (ALQUILER_TIEMPO,
											ALQUILER_TIPO_INMUEBLE,
											ALQUILER_RANGO_M2,
											ALQUILER_UBICACION,
											ALQUILER_RANGO_ETARIO_AGENTE,
                                            ALQUILER_RANGO_ETARIO_INQUILINO,
											ALQUILER_SUCURSAL,
											ALQUILER_AMBIENTES,
											ALQUILER_TIPO_MONEDA,
											ALQUILER_COMISION)
    SELECT 
	    (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(alq.ALQUILER_FECHAINICIO) AND t.TIEMPO_MES = MONTH(alq.ALQUILER_FECHAINICIO) AND t.TIEMPO_DIA = DAY(alq.ALQUILER_FECHAINICIO)),
	    (SELECT tipi.TIPO_INMUEBLE_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Inmueble tipi WHERE tipi.TIPO_INMUEBLE_DESCRIPCION = ti.TIPO_INMUEBLE_DESCRIPCION),
	    (SELECT rm.RANGO_M2_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_M2 rm WHERE rm.RANGO_M2_DESCRIPCION = GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL)),
	    (SELECT u.UBICACION_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ubicacion u WHERE u.UBICACION_PROVINCIA = pr.PROVINCIA_NOMBRE AND u.UBICACION_LOCALIDAD = lo.LOCALIDAD_NOMBRE AND u.UBICACION_BARRIO = ba.BARRIO_NOMBRE),
	    (SELECT rea.RANGO_ETARIO_AGENTE_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_Etario_Agente rea WHERE rea.RANGO_ETARIO_AGENTE_DESCRIPCION = GUISO_DE_LENTEJAS.rangoEtario_fx(ai.AGENTE_INMOBILIARIO_FECHA_NACIMIENTO)),
		(SELECT rei.RANGO_ETARIO_INQUILINO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Rango_Etario_Inquilino rei WHERE rei.RANGO_ETARIO_INQUILINO_DESCRIPCION = GUISO_DE_LENTEJAS.rangoEtario_fx(inq.INQUILINO_FECHA_NAC)),
	    (SELECT su.SUCURSAL_CODIGO FROM GUISO_DE_LENTEJAS.BI_Sucursal su WHERE su.SUCURSAL_NOMBRE = s.SUCURSAL_NOMBRE),
	    (SELECT amb.AMBIENTE_CODIGO FROM GUISO_DE_LENTEJAS.BI_Ambiente amb WHERE amb.AMBIENTE_DESCRIPCION = am.AMBIENTE_DESCRIPCION),
	    (SELECT mon.TIPO_MONEDA_ID FROM GUISO_DE_LENTEJAS.BI_Tipo_Moneda mon WHERE mon.TIPO_MONEDA_DESCRIPCION = mo.MONEDA_DESCRIPCION),
	    SUM(alq.ALQUILER_COMISION)
	    FROM GUISO_DE_LENTEJAS.ALQUILER alq
	    INNER JOIN GUISO_DE_LENTEJAS.ANUNCIO a ON a.ANUNCIO_ID = alq.ALQUILER_ANUNCIO 
	    INNER JOIN GUISO_DE_LENTEJAS.INMUEBLE i ON i.INMUEBLE_NUMERO = a.ANUNCIO_INMUEBLE
	    INNER JOIN GUISO_DE_LENTEJAS.TIPO_INMUEBLE ti ON ti.TIPO_INMUEBLE_ID = i.INMUEBLE_TIPOINMUEBLE
	    INNER JOIN GUISO_DE_LENTEJAS.BARRIO ba ON ba.BARRIO_ID = i.INMUEBLE_BARRIO 
	    INNER JOIN GUISO_DE_LENTEJAS.LOCALIDAD lo ON lo.LOCALIDAD_ID = ba.BARRIO_LOCALIDAD 
        INNER JOIN GUISO_DE_LENTEJAS.PROVINCIA pr ON pr.PROVINCIA_ID = lo.LOCALIDAD_PROVINCIA
        INNER JOIN GUISO_DE_LENTEJAS.AGENTE_INMOBILIARIO ai ON ai.AGENTE_INMOBILIARIO_ID = a.ANUNCIO_AGENTE_INMOBILIARIO 
        INNER JOIN GUISO_DE_LENTEJAS.SUCURSAL s ON s.SUCURSAL_ID = ai.AGENTE_INMOBILIARIO_SUCURSAL
		INNER JOIN GUISO_DE_LENTEJAS.INQUILINO inq ON inq.INQUILINO_ID = alq.ALQUILER_INQUILINO 
        INNER JOIN GUISO_DE_LENTEJAS.AMBIENTE am ON am.AMBIENTE_ID = i.INMUEBLE_AMBIENTE
	    INNER JOIN GUISO_DE_LENTEJAS.MONEDA mo ON mo.MONEDA_ID = a.ANUNCIO_MONEDA 
    GROUP BY alq.ALQUILER_FECHAINICIO , ti.TIPO_INMUEBLE_DESCRIPCION , GUISO_DE_LENTEJAS.rangoM2_fx(i.INMUEBLE_SUPERFICIETOTAL), mo.MONEDA_DESCRIPCION ,  ba.BARRIO_NOMBRE , lo.LOCALIDAD_NOMBRE  , pr.PROVINCIA_NOMBRE , am.AMBIENTE_DESCRIPCION, s.SUCURSAL_NOMBRE, GUISO_DE_LENTEJAS.rangoEtario_fx(ai.AGENTE_INMOBILIARIO_FECHA_NACIMIENTO), GUISO_DE_LENTEJAS.rangoEtario_fx(inq.INQUILINO_FECHA_NAC)
END
PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ALQUILERES ejecutado')
GO

CREATE PROCEDURE GUISO_DE_LENTEJAS.BI_MIGRAR_PAGOS_ALQUILER
AS
BEGIN
    INSERT INTO GUISO_DE_LENTEJAS.BI_Hecho_Pago_Alquiler (PAGO_FECHA_PAGO, PAGO_FECHA_VENCIMIENTO)
        SELECT 
        (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(pa.PAGO_ALQUILER_FECHA_PAGO) AND t.TIEMPO_MES = MONTH(pa.PAGO_ALQUILER_FECHA_PAGO) AND t.TIEMPO_DIA = DAY(pa.PAGO_ALQUILER_FECHA_PAGO)),
        (SELECT t.TIEMPO_CODIGO FROM GUISO_DE_LENTEJAS.BI_Tiempo t WHERE t.TIEMPO_ANIO = YEAR(pa.PAGO_ALQUILER_FECHA_VENCIMIENTO) AND t.TIEMPO_MES = MONTH(pa.PAGO_ALQUILER_FECHA_VENCIMIENTO) AND t.TIEMPO_DIA = DAY(pa.PAGO_ALQUILER_FECHA_VENCIMIENTO))           
        FROM GUISO_DE_LENTEJAS.PAGO_ALQUILER pa
    GROUP BY pa.PAGO_ALQUILER_FECHA_PAGO, pa.PAGO_ALQUILER_FECHA_VENCIMIENTO
END
PRINT('Stored Procedure GUISO_DE_LENTEJAS.BI_MIGRAR_PAGOS_ALQUILER ejecutado')
GO

/*EJECUTAR*/
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_DIMENSION_TIEMPO
EXECUTE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_AGENTES
EXECUTE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_ETARIOS_INQUILINOS
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_INMUEBLES
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_OPERACIONES
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_UBICACION
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_TIPOS_MONEDAS
EXECUTE GUISO_DE_LENTEJAS.BI_INSERTAR_RANGOS_M2
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_SUCURSALES
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_AMBIENTES
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ANUNCIOS
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_VENTAS
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_HECHOS_ALQUILERES
EXECUTE GUISO_DE_LENTEJAS.BI_MIGRAR_PAGOS_ALQUILER
--soy 9 vistas